---
title: "References"
---

<a name="jennisonturnbull">Jennison, C., & Turnbull, B.W. (1999). Group Sequential Methods with Applications to Clinical Trials (1st ed.). Chapman and Hall/CRC. https://doi.org/10.1201/9780367805326</a>

<a name="pass">NCSS, LLC. Assurance for Non-Inferiority Tests for the Difference Between Two Proportions. In *PASS Sample Size Software Documentation* (pp. 289-1-289–31). Retrieved from <https://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/Assurance_for_Non-Inferiority_Tests_for_the_Difference_Between_Two_Proportions.pdf>.</a>

<a name="sas">SAS Institute Inc. 2016. Base SAS® 9.4 Procedures Guide: Statistical Procedures, Sixth Edition. Cary, NC: SAS Institute Inc.</a>

<a name="gelman">Prior distributions for variance parameters in hierarchical models”, Andrew Gelman, Bayesian Analysis 2006, 1, Number 3 pp 515-533</a>

<a name="dunnett"> Dunnett CW. A multiple comparison procedure for comparing several treatments with a control. Journal of the American Statistical Association. 1955; 50: 1096-1121.</a>

<a name="agresti">Agresti, A. 2002.  Categorical Data Analysis. Second Edition. Wiley.</a>

<a name="mee">Mee, R. W. 1984. Confidence bounds for the difference between two probabilities. Biometrics. 40, 1175-1176.</a>

<a name="nurminen">Nurminen, M. 1986. Confidence intervals for the ratio and
difference of two binomial proportions. Biometrics. 42, 675-676.</a>
