---
title: "Ordinal Endpoint QOIs"
subtitle: "QOIs specific to ordinal endpoints."
title-block-banner: '#125740'
title-block-banner-color: white
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: false
    number-depth: 4
---

The FACTS Ordinal Engine features several special quantities of interest. 

# Posterior probability QOIs

The posterior probability QOIs available depend on whether the user has chosen to
model the ordinal endpoint with the cumulative logistic family or with 
independent Dirichlet distributions.  

## Cumulative logistic modeling

When the cumulative logistic family is in use, each arm other than control has 
an odds ratio parameter relative to control.  Posterior probability QOIs are 
defined based on these odds ratios.  By default, the following 
posterior probability QOIs are available, (here $OR_d$ is $\exp(\theta_d)$ where 
the $\theta_d$'s are the parameters defined in the dose-response model):  

 - The probability of being better than control, which is 
 [Pr($OR_d > 1$)]{.fake-code-block} when large values of the ordinal index are 
 good, or [Pr($OR_d < 1$)]{.fake-code-block} when small values are good.
 
 - The probability of being better than control by a clinically significant 
 difference, which is [Pr($OR_d - 1 > CSD$)]{.fake-code-block} when large values 
 are good, or [Pr($OR_d - 1 < -CSD$)]{.fake-code-block} when small values are 
 good.  The CSD is entered by the user in the Standard Evaluation Variables 
 section of the Quantities of Interest tab.

## Dirichlet modeling

When the user has selected independent Dirichlet modeling for the ordinal 
endpoint, the posterior probability QOIs are based on expected utility.  The 
default posterior probability QOIs are:

- The probability of being better than control with respect to expected utility, 
which is [Pr($EU_d > EU_{Control}$)]{.fake-code-block}.  Here 
$EU_d = \sum_{k=1}^K p^d_k U_k$, where $p^d_k$ is the probability of ordinal 
outcome $k$ for arm $d$ and where $U_k$ is the utility for outcome $k$.  

- The probability of being better than control by a clinical significant difference, 
which is [Pr($EU_d > EU_{Control} + CSD$)]{.fake-code-block} regardless of
whether large or small values of the ordinal endpoint are good (large values of 
utility are always good).  The CSD is entered by the user in the Standard 
Evaluation Variables section of the Quantities of Interest tab.

# $p$-values

The Ordinal Engine has the following different frequentist final analyses available.
If there are multiple experimental arms, the $p$-values can optionally be adjusted 
using the Bonferroni correction.  The $p$-values may handle missing values by 
ignoring them or by imputing a specific ordinal outcome chosen by the user.  

## Utility $t$-test

One option is to perform a $t$-test on the utility values observed, comparing 
each experimental arm to control, in the same way as with a continuous endpoint.  

## Wilcoxon-Mann-Whitney test

FACTS will also perform a Wilcoxon-Mann-Whitney (rank sum) test comparing each 
experimental arm to control. FACTS adjusts for ties in computing the $p$-value.   

## Proportional odds likelihood ratio test

FACTS will also perform a likelihood ratio test based on the proportional odds 
model, comparing each experimental arm to control.  It fits a multinomial model 
to both arms together, and also fits a model where the experimental arm has a 
single proportional odds model deviation from control, and compares twice the logged 
ratio of maximized likelihoods to the chi-squared distribution with one degree of 
freedom.  In practice, this test will often give similar results to the Wilcoxon 
test.  (See, for example, blog posts by Harrell.)

## Dichotomized ordinal test

FACTS will also test whether the probability of a "good" outcome is larger for 
an experimental arm than it is for control.  The user defines a "good" outcome 
using the "Definition of Success" selector in the "Standard Evaluation Variables"
section.  The test is the same as for a dichotomous endpoint.  

Dichotomizing an ordinal outcome is rarely a good choice because much 
of the information in the ordinal outcome is wasted.  See, for example, 
Podcast by Scott Berry.  FACTS simulations can be useful in demonstrating the 
reduction in power when an ordinal endpoint is dichotomized.   

# Bayesian Predictive Probabilities

Bayesian predictive probabilities are available for any of the four $p$-value-based 
frequentist final analyses described above.  As with other endpoints, these can 
be predictions of the result of the current trial, or a separate two-arm trial.  
The current trial predictions can refer either to an analysis of the patients 
currently enrolled but after follow-up is complete, or at the maximum sample 
size for the trial.  

Here are a few notes about the different predictive probabilities.  

- Predictive probabilities for the proportional odds likelihood ratio test are 
likely to be more time-consuming, and less accurate, to simulate than the other 
$p$-values.  These predictive probabilities require simulating a large number of 
final data sets, computing the test statistic for each, and counting how many 
achieved the desired significance level.  We recommend substituting the 
Wilcoxon test while the design is being developed (and maybe permanently); its
results should be similar.  

- Predictive probabilities for the Wilcoxon test:
Both future trial and current trial predictive probabilities for the Wilcoxon 
test are computed using formulas developed by Graves for use in simulating 
trials designed by Berry Consultants including SEPSIS-ACT.  The approach is to write
the Wilcoxon-Mann-Whitney as a sum, over pairs of patients, of indicators that 
an experimental arm patient has a better outcome than a control arm patients, 
and then correctly computes the predictive mean and variance of this sum as a 
function of the probabilities of each outcome for each arm.  The results are 
then averaged over a large number of Markov chain Monte Carlo samples of 
outcome probabilities.  The predictive probabilities computed in this way are 
very accurate, the only exception is when there are a very small number of future 
patients whose data are yet to be collected.  

## Current Trial Bayesian Predictive Probabilities

For general discussion of current trial Bayesian predictive probabilities, 
see the core QOIs page.  

## Future Trial Bayesian Predictive Probabilities

For general discussion of future trial Bayesian predictive probabilities, 
see the core QOIs page.  

## Conditional Power

Conditional power in trials with an ordinal endpoint 
will be added in a future release of FACTS Ordinal.  

# Decision Quantities

Decision quantities in FACTS Ordinal operate similarly to decision quantities with 
other FACTS endpoints.

# Standard Evaluation Variables



