---
title: "Get FACTS"
subtitle: "Innovative Simulations for Innovative Trials"
title-block-banner: '#125740'
title-block-banner-color: white
---

[FACTS](https://www.berryconsultants.com/software/facts){target="_blank"} (Fixed and Adaptive Clinical Trial Simulator) is the industry’s most powerful tool for adaptive and fixed trial design. It enables biostatisticians to design, simulate, and optimize trials with speed and precision, reducing risk and driving innovative, data-driven decisions. Over half of the top 20 largest pharmaceutical companies in the world and more than 30 academic institutions trust FACTS to assist them in the design, simulation, and implementation of trials.

### Industry

We offer a 3-months free FACTS Evaluation License to showcase the power and features of our FACTS simulation tool. Please [contact us](../contact/index.qmd) to get a free demo, or learn more about this offer and our regular licenses.

### Academia / Charities / Regulatory Bodies / Government

To academic and other non-profit research institutions and regulatory bodies, we will generally offer a free FACTS license under certain conditions. Please [contact us](../contact/index.qmd) to see if your organization qualifies.
