project:
  type: website

website:
  title: ""
  navbar:
    logo: "media/FACTS_logo.jpg"
    left:
      - href: index.qmd
        text: Home
      - href: why.qmd
        text: Why FACTS?
      - href: start.qmd
        text: Getting Started
      - href: references.qmd
        text: References
      - href: webinars.qmd
        text: Webinars
    right:
      - href: documentation.qmd
        text: Documentation
      - href: news.qmd
        text: News
      - href: releases.qmd
        text: Release Notes
      - href: contact.qmd
        text: Contact Us

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

