project:
  type: website
  output-dir: docs

website:
  favicon: media/FACTS_icon.png
  search:
    location: navbar
    type: overlay
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTSLogo.png"
    pinned: true
    left:
      - href: introduction/index.qmd
        text: "Introduction"
      - href: documentation/index.qmd
        text: "Documentation"
      - href: concepts/index.qmd
        text: "Concepts"

    right:
      - href: blog/index.qmd
        text: "Blog"
      - href: versions/index.qmd
        text: "Versions"
      - href: get/index.qmd
        text: "Get FACTS"
      - href: contact/index.qmd
        text: Contact


  sidebar:

    - id: Contact
      title: "Contact"
      style: "floating"
      collapse-level: 1
      contents:
        - contact/index.qmd

    - id: Blog
      title: "Blog"
      style: "floating"
      collapse-level: 1
      contents:
        - blog/index.qmd

    - id: Get FACTS
      title: "Get FACTS"
      style: "floating"
      collapse-level: 1
      contents:
        - get/index.qmd

    - id: Concepts
      title: "Concepts"
      style: "floating"
      collapse-level: 1
      contents:
        - concepts/index.qmd
        - auto: concepts/*.qmd
        - section: concepts/adaptiveDesigns/index.qmd
          contents:
            - auto: concepts/adaptiveDesigns/*.qmd
        - section: concepts/bayes/index.qmd
          contents:
            - auto: concepts/bayes/*.qmd
        - section: FACTS Tips and Tricks
          contents:
            - auto: concepts/facts/*.qmd

    - id: Start
      title: "Introduction"
      style: "floating"
      collapse-level: 1
      contents:
        - introduction/index.qmd
        - section: Getting Started
          contents:
            - auto: introduction/gettingStarted/*.qmd
        - section: Tutorials
          contents:
            - section: Phase I Trials
              contents:
                - auto: introduction/tutorials/phase1/*.qmd
            - section: Phase I/II Trials
              contents:
                - auto: introduction/tutorials/phase12/*.qmd
            - section: Phase II Trials
              contents:
                - auto: introduction/tutorials/phase2/*.qmd
            - section: Phase II/III Trials
              contents:
                - auto: introduction/tutorials/phase23/*.qmd
            - section: Phase III Trials
              contents:
                - auto: introduction/tutorials/phase3/*.qmd
        - auto: introduction/*.qmd

    - id: Documentation
      title: "Documentation"
      style: "floating"
      collapse-level: 3
      contents:
        - documentation/index.qmd
        - section: Version 7.1
          contents:
            - section: User Guides
              contents:
              - section: documentation/v71/userguides/core/index.qmd
                contents:
                  - section: Study
                    contents:
                    - text: Continuous
                      href: documentation/v71/userguides/core/study/continuous.qmd
                    - text: Dichotomous
                      href: documentation/v71/userguides/core/study/dichotomous.qmd
                    - text: Time-to-Event
                      href: documentation/v71/userguides/core/study/tte.qmd
                  - section: documentation/v71/userguides/core/vsr/index.qmd
                    contents:
                    - text: Continuous
                      href: documentation/v71/userguides/core/vsr/continuous.qmd
                    - text: Dichotomous
                      href: documentation/v71/userguides/core/vsr/dichotomous.qmd
                    - text: Time-to-Event
                      href: documentation/v71/userguides/core/vsr/tte.qmd
                  - text: Execution
                    href: documentation/v71/userguides/core/execution.qmd
                  - documentation/v71/userguides/core/qois.qmd
                  - section: Design
                    href: documentation/v71/userguides/core/design/index.qmd
                    contents:
                    - documentation/v71/userguides/core/design/doseresponse.qmd
                    - documentation/v71/userguides/core/design/frequentistanalysis.qmd
                    - section: documentation/v71/userguides/core/longitudinalmodels/index.qmd
                      contents:
                      - text: Continuous
                        href: documentation/v71/userguides/core/longitudinalmodels/continuous.qmd
                      - text: Dichotomous
                        href: documentation/v71/userguides/core/longitudinalmodels/dichotomous.qmd
                      - text: Time-to-Event
                        href: documentation/v71/userguides/core/longitudinalmodels/tte.qmd
                    - documentation/v71/userguides/core/design/allocation.qmd
                    - documentation/v71/userguides/core/design/interims.qmd
                    - documentation/v71/userguides/core/design/successfutility.qmd
                  - section: documentation/v71/userguides/core/simulation/index.qmd
                    contents:
                    - text: Continuous/Dichotomous
                      href: documentation/v71/userguides/core/simulation/contanddichot.qmd
                    - text: Time-to-Event
                      href: documentation/v71/userguides/core/simulation/tte.qmd
                  - documentation/v71/userguides/core/analysis.qmd
              - documentation/v71/userguides/platform.qmd
              - documentation/v71/userguides/crm.qmd
              - documentation/v71/userguides/de.qmd
              - auto: documentation/v71/userguides/*.qmd
            - section: Examples
              contents:
                - section: CRM
                  # contents:
                  #   - auto: documentation/v71/examples/CRM/*.qmd
                - section: Staged
                  # contents:
                  #   - auto: documentation/v71/examples/Staged/*.qmd
            - auto: documentation/v71/*.qmd

    - id: Versions
      title: "Versions"
      style: "floating"
      collapse-level: 1
      contents:
        - versions/index.qmd
        - auto: versions/*.qmd
        - section: FACTS 7 Release Notes
          contents:
            - versions/v7/facts711.qmd
            - versions/v7/facts710.qmd
            - versions/v7/facts700.qmd
        - section: FACTS 6 Release Notes
          contents:
            - versions/v6/facts650.qmd
            - versions/v6/facts641.qmd
            - versions/v6/facts640.qmd
            - versions/v6/facts630.qmd
            - versions/v6/facts625.qmd
            - versions/v6/facts624.qmd
            - versions/v6/facts620.qmd
            - versions/v6/facts616.qmd
            - versions/v6/facts610.qmd
            - versions/v6/facts600.qmd

format:
  html:
    theme: default
    css: styles.css
    include-in-header:
      - fonts.html
      - header.html
    page-layout: full
    toc: true
    include-after-body: footer.html
    grid:
      sidebar-width: 300px
      body-width: 2000px
      margin-width: 300px
      gutter-width: 1.5rem

editor: source

resources:
  - CNAME

bibliography: references.bib
