project:
  type: website

website:
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:Start
      - sidebar:Userguides
      - sidebar:Examples
      - sidebar:Encyclopedia
     
    right:
      - href: news.qmd
        text: News
      - href: webinars.qmd
        text: Webinars
      - href: releases.qmd
        text: Release Notes
      - href: contact.qmd
        text: Contact Us

    
      
  sidebar:
    - id: Encyclopedia
      title: "Encyclopedia"
      style: "docked"
      collapse-level: 2
      contents:
        - encyclopedia.qmd
        - section: Bayesian Statistics
          contents:
            - auto: encyclopedia/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: encyclopedia/adaptiveDesigns/*.qmd
    - id: Start
      title: "Getting Started"
      style: "docked"
      collapse-level: 2
      contents:
        - start.qmd
        - installation.qmd
    - id: Userguides
      title: "User Guides"
      style: "docked"
      collapse-level: 2
      contents:
        - userguides/crm.qmd
    - id: Examples
      title: "Examples"
      style: "docked"
      collapse-level: 2
      contents:
        - examples.qmd
        - section: Dose Escalation
          contents:
            - auto: examples/de/*.qmd
        - section: Enrichment Designs
          contents:
            - auto: encyclopedia/enrichment/*.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

