project:
  type: website
  output-dir: docs

website:
  search: 
    location: navbar
    type: overlay
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: gettingStarted/index.qmd
        text: "Getting Started"
      - href: documentation/index.qmd
        text: "Documentation"
      - href: encyclopedia/index.qmd
        text: "Encyclopedia"
     
    right:
      - href: news/index.qmd
        text: News
      - href: releaseNotes/index.qmd
        text: "Release Notes"
      - href: get.qmd
        text: Get FACTS
      - href: contact.qmd
        text: Contact
    
      
  sidebar:
    - id: Encyclopedia
      title: "Encyclopedia"
      style: "docked"
      collapse-level: 1
      contents:
        - encyclopedia/index.qmd
        - auto: encyclopedia/*.qmd
        - section: Bayesian Statistics
          contents:
            - auto: encyclopedia/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: encyclopedia/adaptiveDesigns/*.qmd
    - id: Start
      title: "Getting Started"
      style: "docked"
      collapse-level: 1
      contents:
        - gettingStarted/index.qmd
        - auto: gettingStarted/*.qmd
        - section: Tutorials
          contents: 
            - auto: gettingStarted/tutorials/*.qmd
    - id: Documentation
      title: "Documentation"
      style: "docked"
      collapse-level: 1
      contents:
        - documentation/index.qmd
        - section: "Version 7.1.0"
        - auto: documentation/*.qmd
        - section: User Guides
          contents:
            - auto: documentation/userguides/*.qmd
        - section: Examples
          contents:
            - auto: userguides/examples/*.qmd
            - section: CRM
              contents: 
                - auto: documentation/examples/CRM/*.qmd
            - section: Staged
              contents: 
                - auto: documentation/examples/Staged/*.qmd
    - id: Releases
      title: "Release Notes"
      style: "docked"
      collapse-level: 1
      contents:
        - releaseNotes/index.qmd
        - section: FACTS 7 Release Notes
          contents:
            - auto: releaseNotes/v7/*.qmd
        - section: FACTS 6 Release Notes
          contents:
            - auto: releaseNotes/v6/*.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: source

resources:
  - CNAME

bibliography: references.bib