project:
  type: website
  output-dir: docs

website:
  search:
    location: navbar
    type: overlay
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: introduction/index.qmd
        text: "Introduction"
      - href: documentation/index.qmd
        text: "Documentation"
      - href: concepts/index.qmd
        text: "Concepts"

    right:
      - href: notes/index.qmd
        text: "Field Notes"
      - href: releaseNotes/index.qmd
        text: "Release Notes"
      - href: get.qmd
        text: Get FACTS
      - href: contact.qmd
        text: Contact


  sidebar:
    - id: Concepts
      title: "Concepts"
      style: "floating"
      collapse-level: 2
      contents:
        - concepts/index.qmd
        - auto: concepts/*.qmd
        - section: Bayesian Statistics
          contents:
            - auto: concepts/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: concepts/adaptiveDesigns/*.qmd
        - section: FACTS Tips and Tricks
          contents:
            - auto: concepts/facts/*.qmd
    - id: Start
      title: "Introduction"
      style: "floating"
      collapse-level: 2
      contents:
        - introduction/index.qmd
        - section: Getting Started
          contents:
            - auto: introduction/gettingStarted/*.qmd
        - section: Tutorials
          contents:
            - auto: introduction/tutorials/*.qmd
        - section: Webinars
          contents:
            - auto: introduction/webinars/*.qmd
    - id: Documentation
      title: "Documentation"
      style: "floating"
      collapse-level: 3
      contents:
        - documentation/index.qmd
        - documentation/glossary.qmd
        - section: Version 7.1
          contents:
            - section: User Guides
              contents:
              - section: documentation/v71/userguides/core/index.qmd
                contents:
                  - documentation/v71/userguides/core/study.qmd
                  - section: Virtual Subject Response
                    contents:
                    - documentation/v71/userguides/core/vsr/continuous.qmd
                    - documentation/v71/userguides/core/vsr/dichotomous.qmd
                    - documentation/v71/userguides/core/vsr/tte.qmd
                  - documentation/v71/userguides/core/execution.qmd
                  - documentation/v71/userguides/core/qois.qmd
                  - section: documentation/v71/userguides/core/design/index.qmd
                    contents:
                    - documentation/v71/userguides/core/design/doseresponse.qmd
                    - documentation/v71/userguides/core/design/frequentistanalysis.qmd
                    - section: documentation/v71/userguides/core/longitudinalmodels/index.qmd
                      contents:
                      - documentation/v71/userguides/core/longitudinalmodels/continuous.qmd
                      - documentation/v71/userguides/core/longitudinalmodels/dichotomous.qmd
                      - documentation/v71/userguides/core/longitudinalmodels/tte.qmd
                    - documentation/v71/userguides/core/design/allocation.qmd
                    - documentation/v71/userguides/core/design/interims.qmd
                    - documentation/v71/userguides/core/design/successfutility.qmd
                  - documentation/v71/userguides/core/simulation.qmd
                  - documentation/v71/userguides/core/analysis.qmd
              - auto: documentation/v71/userguides/*.qmd
            - section: Examples
              contents:
                - section: CRM
                  contents:
                    - auto: documentation/v71/examples/CRM/*.qmd
                - section: Staged
                  contents:
                    - auto: documentation/v71/examples/Staged/*.qmd
        - documentation/references.qmd
    - id: Releases
      title: "Release Notes"
      style: "floating"
      collapse-level: 1
      contents:
        - releaseNotes/index.qmd
        - section: FACTS 7 Release Notes
          contents:
            - releaseNotes/v7/facts711.qmd
            - releaseNotes/v7/facts710.qmd
            - releaseNotes/v7/facts700.qmd
        - section: FACTS 6 Release Notes
          contents:
            - releaseNotes/v6/facts650.qmd
            - releaseNotes/v6/facts641.qmd
            - releaseNotes/v6/facts640.qmd
            - releaseNotes/v6/facts630.qmd
            - releaseNotes/v6/facts625.qmd
            - releaseNotes/v6/facts624.qmd
            - releaseNotes/v6/facts620.qmd
            - releaseNotes/v6/facts616.qmd
            - releaseNotes/v6/facts610.qmd
            - releaseNotes/v6/facts600.qmd

format:
  html:
    theme: default
    css: styles.css
    include-in-header: fonts.html
    page-layout: full
    toc: true
    include-after-body: footer.html
    grid:
      sidebar-width: 300px
      body-width: 2000px
      margin-width: 300px
      gutter-width: 1.5rem

editor: source

resources:
  - CNAME

bibliography: references.bib
