project:
  type: website
  output-dir: docs

website:
  search: 
    location: navbar
    type: overlay
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: gettingStarted/firstSteps.qmd
        text: "Getting Started"
      - href: examples/about.qmd
        text: "Examples"
      - href: userguides/about.qmd
        text: "User Guides"
      - href: encyclopedia/about.qmd
        text: "Encyclopedia"
     
    right:
      - href: news/about.qmd
        text: News
      - href: releaseNotes/about.qmd
        text: "Release Notes"
      - href: get.qmd
        text: Get FACTS
      - href: contact.qmd
        text: Contact
    
      
  sidebar:
    - id: Encyclopedia
      title: "Encyclopedia"
      style: "docked"
      collapse-level: 1
      contents:
        - encyclopedia/about.qmd
        - section: Bayesian Statistics
          contents:
            - auto: encyclopedia/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: encyclopedia/adaptiveDesigns/*.qmd
    - id: Webinars
      title: "Webinars"
      style: "docked"
      collapse-level: 1
      contents:
        - webinars/about.qmd
    - id: Start
      title: "Getting Started"
      style: "docked"
      collapse-level: 1
      contents:
        - auto: gettingStarted/*.qmd
    - id: Examples
      title: "Examples"
      style: "docked"
      collapse-level: 1
      contents:
        - examples/about.qmd
        - section: FACTS 7.1.0
          contents:
            - section: Dose Escalation
              contents:
                - auto: examples/facts710/de/*.qmd
            - section: Enrichment Designs
              contents:
                - auto: examples/facts710/enrichment/*.qmd
        - section: FACTS 7.0.0
          contents:
            - section: Dose Escalation
              contents:
                - auto: examples/facts700/de/*.qmd
            - section: Enrichment Designs
              contents:
                - auto: examples/facts700/enrichment/*.qmd
    - id: Userguides
      title: "User Guides"
      style: "docked"
      collapse-level: 1
      contents:
        - userguides/about.qmd
        - userguides/glossary.qmd
        - section: FACTS 7.1.0
          contents:
            - auto: userguides/facts710/*.qmd
        - section: FACTS 7.0.0
          contents:
            - auto: userguides/facts700/*.qmd
    - id: Releases
      title: "Release Notes"
      style: "docked"
      collapse-level: 1
      contents:
        - releaseNotes/about.qmd
        - section: FACTS 7 Release Notes
          contents:
            - releaseNotes/facts700.qmd
        - section: FACTS 6 Release Notes
          contents:
            - releaseNotes/facts650.qmd
            - releaseNotes/facts641.qmd
            - releaseNotes/facts640.qmd
            - releaseNotes/facts630.qmd
            - releaseNotes/facts625.qmd
            - releaseNotes/facts624.qmd
            - releaseNotes/facts620.qmd
            - releaseNotes/facts616.qmd
            - releaseNotes/facts610.qmd
            - releaseNotes/facts600.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: source

resources:
  - CNAME

bibliography: references.bib