project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: gettingStarted/firstSteps.qmd
        text: "Getting Started"
      - href: userguides/facts700/crm.qmd
        text: "User Guides"
      - href: examples/about.qmd
        text: "Examples"
      - href: encyclopedia/about.qmd
        text: "Encyclopedia"
     
    right:
      - href: news/about.qmd
        text: News
      - href: releaseNotes/FACTS7/facts700.qmd
        text: "Release Notes"
      - href: individualPages/pricing.qmd
        text: Pricing
      - href: individualPages/contact.qmd
        text: Contact
    
      
  sidebar:
    - id: Encyclopedia
      title: "Encyclopedia"
      style: "docked"
      collapse-level: 1
      contents:
        - encyclopedia/about.qmd
        - section: Bayesian Statistics
          contents:
            - auto: encyclopedia/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: encyclopedia/adaptiveDesigns/*.qmd
    - id: Webinars
      title: "Webinars"
      style: "docked"
      collapse-level: 1
      contents:
        - webinars/about.qmd
    - id: Start
      title: "Getting Started"
      style: "docked"
      collapse-level: 1
      contents:
        - auto: gettingStarted/*.qmd
    - id: Userguides
      title: "User Guides"
      style: "docked"
      collapse-level: 1
      contents:
        - section: FACTS 7.1.0
          contents:
            - auto: userguides/facts710/*.qmd
        - section: FACTS 7.0.0
          contents:
            - auto: userguides/facts700/*.qmd
    - id: Examples
      title: "Examples"
      style: "docked"
      collapse-level: 1
      contents:
        - examples/about.qmd
        - section: Dose Escalation
          contents:
            - auto: examples/de/*.qmd
        - section: Enrichment Designs
          contents:
            - auto: examples/enrichment/*.qmd
    - id: Releases
      title: "Release Notes"
      style: "docked"
      collapse-level: 1
      contents:
        - section: FACTS 7 Release Notes
          contents:
            - releaseNotes/FACTS7/facts700.qmd
        - section: FACTS 6 Release Notes
          contents:
            - releaseNotes/FACTS6/facts650.qmd
            - releaseNotes/FACTS6/facts641.qmd
            - releaseNotes/FACTS6/facts640.qmd
            - releaseNotes/FACTS6/facts630.qmd
            - releaseNotes/FACTS6/facts625.qmd
            - releaseNotes/FACTS6/facts624.qmd
            - releaseNotes/FACTS6/facts620.qmd
            - releaseNotes/FACTS6/facts616.qmd
            - releaseNotes/FACTS6/facts610.qmd
            - releaseNotes/FACTS6/facts600.qmd

format:
  html:
    theme: cosmo

editor: source

resources:
  - CNAME
