project:
  type: website
  output-dir: docs

website:
  search: 
    location: navbar
    type: overlay
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: gettingStarted/index.qmd
        text: "Getting Started"
      - href: documentation/index.qmd
        text: "Documentation"
      - href: concepts/index.qmd
        text: "Concepts"
     
    right:
      - href: notes/index.qmd
        text: "Field Notes"
      - href: releaseNotes/index.qmd
        text: "Release Notes"
      - href: get.qmd
        text: Get FACTS
      - href: contact.qmd
        text: Contact
    
      
  sidebar:
    - id: Concepts
      title: "Concepts"
      style: "floating"
      collapse-level: 2
      contents:
        - concepts/index.qmd
        - auto: concepts/*.qmd
        - section: Bayesian Statistics
          contents:
            - auto: concepts/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: concepts/adaptiveDesigns/*.qmd
        - section: FACTS Tips and Tricks
          contents:
            - auto: concepts/facts/*.qmd
    - id: Start
      title: "Getting Started"
      style: "floating"
      collapse-level: 2
      contents:
        - gettingStarted/index.qmd
        - auto: gettingStarted/*.qmd
        - section: Tutorials
          contents: 
            - auto: gettingStarted/tutorials/*.qmd
    - id: Documentation
      title: "Documentation"
      style: "floating"
      collapse-level: 2
      contents:
        - documentation/index.qmd
        - section: Version 7.1
          contents:
            - section: User Guides
              contents:
                - auto: documentation/v71/userguides/*.qmd
            - section: Examples
              contents:
                - section: CRM
                  contents:
                    - auto: documentation/v71/examples/CRM/*.qmd
                - section: Staged
                  contents:
                    - auto: documentation/v71/examples/Staged/*.qmd
    - id: Releases
      title: "Release Notes"
      style: "floating"
      collapse-level: 1
      contents:
        - releaseNotes/index.qmd
        - section: FACTS 7 Release Notes
          contents:
            - auto: releaseNotes/v7/*.qmd
        - section: FACTS 6 Release Notes
          contents:
            - auto: releaseNotes/v6/*.qmd

format:
  html:
    theme: default
    css: styles.css
    include-in-header: fonts.html
    page-layout: full 
    grid:
      sidebar-width: 200px
      body-width: 2000px
      margin-width: 400px
      gutter-width: 1.5rem

editor: source

resources:
  - CNAME

bibliography: references.bib