project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: start.qmd
        text: "Getting Started"
      - href: userguides/facts700/crm.qmd
        text: "User Guides"
      - href: examples.qmd
        text: "Examples"
      - href: encyclopedia.qmd
        text: "Encyclopedia"
      - href: webinars.qmd
        text: Webinars
     
    right:
      - href: news.qmd
        text: News
      - href: releaseNotes/FACTS7/facts700.qmd
        text: "Release Notes"
      - href: pricing.qmd
        text: Pricing
      - href: contact.qmd
        text: Contact

    
      
  sidebar:
    - id: Encyclopedia
      title: "Encyclopedia"
      style: "docked"
      collapse-level: 1
      contents:
        - encyclopedia.qmd
        - section: Bayesian Statistics
          contents:
            - auto: encyclopedia/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: encyclopedia/adaptiveDesigns/*.qmd
    - id: Start
      title: "Getting Started"
      style: "docked"
      collapse-level: 1
      contents:
        - start.qmd
        - installation.qmd
    - id: Userguides
      title: "User Guides"
      style: "docked"
      collapse-level: 1
      contents:
        - section: FACTS 7.0.0
          contents:
            - auto: userguides/facts700/*.qmd
        - section: FACTS 6.5.0
          contents:
            - auto: userguides/facts650/*.qmd
    - id: Examples
      title: "Examples"
      style: "docked"
      collapse-level: 1
      contents:
        - examples.qmd
        - section: Dose Escalation
          contents:
            - auto: examples/de/*.qmd
        - section: Enrichment Designs
          contents:
            - auto: examples/enrichment/*.qmd
    - id: Releases
      title: "Release Notes"
      style: "docked"
      collapse-level: 1
      contents:
        - section: FACTS 7 Release Notes
          contents:
            - releaseNotes/FACTS7/facts700.qmd
        - section: FACTS 6 Release Notes
          contents:
            - releaseNotes/FACTS6/facts650.qmd
            - releaseNotes/FACTS6/facts641.qmd
            - releaseNotes/FACTS6/facts640.qmd
            - releaseNotes/FACTS6/facts630.qmd
            - releaseNotes/FACTS6/facts625.qmd
            - releaseNotes/FACTS6/facts624.qmd
            - releaseNotes/FACTS6/facts620.qmd
            - releaseNotes/FACTS6/facts616.qmd
            - releaseNotes/FACTS6/facts610.qmd
            - releaseNotes/FACTS6/facts600.qmd

format:
  html:
    theme: cosmo

editor: source

resources:
  - CNAME
