project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: "#FFFFFF"
    logo: "media/FACTS_logo.jpg"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:Start
      - sidebar:Userguides
      - sidebar:Examples
      - sidebar:Encyclopedia
      - href: webinars.qmd
        text: Webinars
     
    right:
      - href: news.qmd
        text: News
      - sidebar:Releases
      - href: licensing.qmd
        text: Licensing
      - href: contact.qmd
        text: Contact Us

    
      
  sidebar:
    - id: Encyclopedia
      title: "Encyclopedia"
      style: "docked"
      collapse-level: 2
      contents:
        - encyclopedia.qmd
        - section: Bayesian Statistics
          contents:
            - auto: encyclopedia/bayes/*.qmd
        - section: Adaptive Designs
          contents:
            - auto: encyclopedia/adaptiveDesigns/*.qmd
    - id: Start
      title: "Getting Started"
      style: "docked"
      collapse-level: 2
      contents:
        - start.qmd
        - installation.qmd
    - id: Userguides
      title: "User Guides"
      style: "docked"
      collapse-level: 2
      contents:
        - userguides/crm.qmd
    - id: Examples
      title: "Examples"
      style: "docked"
      collapse-level: 2
      contents:
        - examples.qmd
        - section: Dose Escalation
          contents:
            - auto: examples/de/*.qmd
        - section: Enrichment Designs
          contents:
            - auto: encyclopedia/enrichment/*.qmd
    - id: Releases
      title: "Release Notes"
      style: "docked"
      collapse-level: 2
      contents:
        - section: FACTS 7 Release Notes
          contents:
            - releaseNotes/FACTS7/facts700.qmd
        - section: FACTS 6 Release Notes
          contents:
            - releaseNotes/FACTS6/facts650.qmd
            - releaseNotes/FACTS6/facts641.qmd
            - releaseNotes/FACTS6/facts640.qmd
            - releaseNotes/FACTS6/facts630.qmd
            - releaseNotes/FACTS6/facts625.qmd
            - releaseNotes/FACTS6/facts624.qmd
            - releaseNotes/FACTS6/facts620.qmd
            - releaseNotes/FACTS6/facts616.qmd
            - releaseNotes/FACTS6/facts610.qmd
            - releaseNotes/FACTS6/facts600.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

