---
title: "FACTS Dose Escalation CRM"
subtitle: "CRM / N-CRM / BLRM (Bayesian Logistic Regression Model)"
bibliography: ../references.bib
format: 
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    number-sections: true
    number-depth: 3
---

References:

\[N-CRM\] = [@neuenschwander2008critical]

\[Backfill\] = [@dehbi2021controlled]

\[Open Enrollment\] = [@broglio2015bayesian]

[Contact us](../contact.qmd)

See the following [example](../examples/de/exampleDE1.qmd)

# Introduction {#sec-introduction}

## Purpose of this document {#sec-purpose}

This document describes how use the FACTS Dose Escalation (DE) N-CRM design engine. It is intended for all end users of the system.

## Scope of this document {#sec-scope}

This document covers the FACTS Dose Escalation N-CRM design engine user interface.

This document does not address the internal workings of the design engines or algorithms, which are addressed in the associated Design Engine Specification. It also does not address the use of FACTS Core Designs or Enrichment Designs, which are covered in other User Guides.

The screenshots provided are specific to a particular installation and may not reflect the exact layout of the information seen by any particular user. They were taken from FACTS 6.3 and later installed on Windows 10. Different versions of Windows or the use of different Windows themes will introduce some differences in appearance. The contents of each tab, however, will be consistent with the software.

## Context of this Issue {#sec-context}

This document has been updated for the version 7.1 release of Dose Escalation FACTS.

## Citing FACTS {#sec-citing}

If writing in LaTex and using Bibtex, if you wish to cite FACTS (thank you!), can we suggest the following:

```default        
@techreport{FACTS71,
  author = {{FACTS Development Team}},
  title = {{FACTS}: Fixed and Adaptive Clinical Trial Simulator},
  year  = {2024},
  month = {11},
  number = {Version 7.1},
  type         = {Computer Software},
  institution = {Berry Consultants LLC},
  address = {Austin, TX},
  note   = {https://www.berryconsultants.com/software/facts/}
}
```

This will result in a reference that, for example in the APA style, will look like the following:

FACTS Development Team (2024). FACTS: Fixed and adaptive clinical trial simulator. Computer Software Version 7.1, Berry Consultants LLC, Austin, TX. https://www.berryconsultants.com/software/facts/.

## Definition of Terms {#sec-definitions}

@tbl-crmterms gives an overview of the acronyms and abbreviations used in this document.

| Name  | Definition  |
|:-------|:-------|
| Cap  | A limit on the number of subjects recruited. In FACTS N-CRM users can specify a cap on the overall number of subjects to be recruited in the trial (the ‘Overall Cap’) and specify stopping rules to define when the trial should stop before it reaches cap. |
| Control   | Is the treatment arm with which the novel treatment(s) are principally being compared. Control may be placebo, or some existing standard of care, or therapy, against which the novel treatment has to be benchmarked in order to determine its likely usefulness.  |
| Core | FACTS Core: A mode of FACTS for designing trials where multiple treatments, (possibly different doses of a novel treatment) are tested against a control and optionally an active comparator. |
| CRM | Continual Reassessment Method – a dose escalation design where the dose-toxicity is estimated using a simple Bayesian model, and the resulting estimates used to control the dose escalation and estimate the Maximum Tolerated Dose (MTD). |
| DE | Dose Escalation: a mode of FACTS where subjects are treated in cohorts and dose escalation is determined by the number of toxicities observed. |
| ED | Enrichment Designs: a mode of FACTS for designing trials where the same treatment is testing in different settings for example different sub-populations or different but related indications. |
| FACTS | Fixed and Adaptive Clinical Trial Simulator. |
| Final Endpoint | The final value, or state, of a subject’s endpoint. |
| GUI | Graphical User Interface, the part of the FACTS application that the user interacts with. |
| Method |	In the FACTS documentation we try to reserve the term ‘method’ for the algorithms used in the simulation (as opposed to the analysis) part of the program. In the analysis part we use the term ‘Model’, see below. |
| Model | In the FACTS documentation we try to reserve the term ‘model’ for the statistical models used in the analysis of the trial data (in the ‘design’ section of the FACTS user interface). Where mathematical algorithms are used for other purposes in FACTS (for instance in the generation of the simulated data) we try to use the term ‘method’. We have found that initially it is very easy for users to be confused between these two parts of FACTS and we feel that using distinct terminology may help to reduce this. |
| MTD | The dose most likely to be the Maximum Tolerated Dose (MTD) – the dose with the highest Pr(MTD). |
| MTD+ | The dose most likely to be the MTD+ – the dose with the highest Pr(MTD+). |
| Pr(MTD) | A dose’s probability of being MTD is the probability that it is the dose with the highest probability of having a toxicity rate in the acceptable toxicity band, and (if a threshold has been specified) does not have a probability of excess or unacceptable toxicity above the threshold. This estimate of MTD is constrained to select one of the available doses. |
| Pr(MTD+) | 	A dose's probability of being the MTD+ is the probability that it is the dose with the highest probability of having a toxicity rate in the acceptable band, and (if a threshold has been specified) does not have a probability of excess or unacceptable toxicity above the threshold. Unlike Pr(MTD), Pr(MTD+) includes estimating whether a dose below or a dose above the range of those being tested is more likely to have a toxicity in the acceptable band than any of the doses in the range. |
| Profile | A profile is a specification of one aspect of a scenario. A scenario is made up of one profile of each of the required types for the type of trial being simulated. FACTS allows the user to specify multiple profiles of each type and then presents all the possible combinations of profiles as scenarios that can be used to drive simulations. |
| Response | The change in a subject’s endpoint compared to their baseline state. |
| Scenario | 	A scenario is the complete specification of the unknown external factors that determine the data observed on the trial and its timing. The exact factors depend on the type of trial being simulated but typically include: <br/> -) the distribution of the final change from base line, or probability of response or rate of events in the different treatment groups <br/> -) the properties of subjects’ early responses and the correlation with their final outcome <br/> -) the rate at which subjects are recruited into the trial <br/> -) the rate at which subjects drop out of the trial. |
| SPEC | The Design Engine Specification, describes the system algorithms, and meaning of parameters. |
| Response | The change in a subject’s endpoint compared to their baseline state. |
| Subject | Someone recruited onto a clinical trial for the purposes of learning about the properties of a treatment. Depending on the type of trial they might be patients or they might be healthy volunteers. |
| Treatment Arm | Subjects on entering the study are randomized to different ‘treatment arms’. Subjects randomized to the same arm receive the same treatment and the responses of the subjects in the arm analyzed to determine the expected response to that treatment, allowing the expected responses to the different treatments to be compared.  |
| UG | The User Guide; describes how to use the system. |

: List of terms used in the CRM user guide {#tbl-crmterms .striped .hover tbl-colwidths="[15,85]"}
