---
title: "FACTS 6.4.1 Release Notes"
subtitle: "October 22, 2021"
bibliography: ../../references.bib
format: 
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    number-sections: true
    number-depth: 3
    css: ../../styles.css
---

# Introduction

Berry Consultants would like to announce a new maintenance release, FACTS 6.4.1. FACTS 6.4.1 contains the following improvements to the FACTS 6.4.0 version. Please [contact us](../../individualPages/contact.qmd) regarding any questions.

# FACTS (Staged) Core Improvements

-   In Time-to-Event designs, the sigmoidal, 3-parameter logistic and hierarchical logistic dose response models have been improved to better handle their respective likelihood evaluation. Namely, when the dose response is non-monotone, or the doses are widely separated.
-   In Time-to-Event designs, the prior for the sigmoidal model’s a2 parameter is now properly applied. As a result, estimates for the sigmoidal model’s a1 and a2 parameter have now been corrected.
-   In Time-to-Event designs, the option to model control separately in TTE predictor models is now applied correctly.
-   In Dichotomous designs, selecting the “Log-odds” parametrization of Posterior Probability QOIs will no longer be rejected as invalid if the Delta values for comparison are outside of \[-1, 1\].
-   In Multiple Endpoint designs with a dichotomous endpoint, Posterior Probability QOIs with the “Log-odds” parametrization will now be computed correctly.
-   A very rare bug has been fixed that occurred when an adaptive design was converted back to a fixed design. The simulator would check the now irrelevant details of the interims and crash.

# FACTS Dose Escalation Improvements

-   In CRM(Efficacy) designs, FACTS files created with FACTS 6.1.0 or older versions will have their “Model control separately” setting correctly migrated over in FACTS 6.4.1 and later versions.
-   In N-CRM designs, the number of beta distribution samples in the specific quantiles prior derivation algorithm has been increased from 1,000 to 10,000.
-   In Dose Escalation designs, Windows and Linux simulation result differences have been resolved.
-   In 2D-CRM dose values of 0 are now allowed with some restrictions:
    a.  any combination where the transformed dose strengths of both drugs are very low (or 0) must be excluded from the study and not have any prior toxicities specified as to have occurred on that combination. The model cannot fit toxicity on such combinations.
    b.  if there is a combination where the transformed dose strength of both drugs are 0, the response model must be re-scaled (using the “Asymptotes” option) so the lower bound is not asymptotically 0, but some value slightly above that (such as 0.0001).
-   In 2D-CRM the prior graph on the Response Model tab can now show the sampled priors for the individual drugs without the lowest dose being plotted (when a dose 0 or very low dose is included this can compress the plot for all the other doses). The x-axis has also been re-labelled to make it clear the doses are being plotted at the log of their transformed dose values.
-   In N-CRM if using Open Enrolment and Backfill, the “Max Study Allocation for Escalation” was not being respected, this is fixed in FACTS 6.4.1.

# FACTS Enrichment Design Improvements

-   FACTS will no longer error when running multiple scenarios when using external data files.

# Framework Improvements

-   Simulation of FACTS files stored on a shared drive will be handled more robustly in the case of intermittent connectivity to the shared drive.
-   Renaming of FACTS analyses on the Analysis tab will now correctly handle the situation when the analysis name has been unchanged.
