---
title: "FACTS 6.0.0 Release Notes"
subtitle: "March 22, 2017"
bibliography: ../../references.bib
format: 
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    number-sections: true
    number-depth: 3
    css: ../../styles.css
---

# Introducing FACTS 6.0.0

Berry Consultants is delighted to announce that FACTS 6.0.0 is ready for release!

Building on FACTS 5, FACTS 6.0.0 adds a new simulation type: “FACTS Staged Design”.

-   FACTS “Staged Design” is a simulator that runs a “FACTS Core” simulation followed by a second “FACTS Core” simulation that can take decisions based on the result of the first simulation and include data from the first simulation. This allows, for example, the simulation of a Phase II trial followed by a Phase III trial, whether as separate trials or as a seamless Phase II/III.
-   FACTS Enrichment Designs includes the flexibility over the timing of interims and the ability to set different decision thresholds at different interims.

FACTS 6.0.0 is fully backwards compatible with FACTS 5 – it can load and run all your FACTS 5 designs – and then add new FACTS 6.0.0 features to them. In particular you can load a FACTS Core design into FACTS Staged Design as the starting point for the design of the first stage. You can have FACTS 5 and FACTS 6.0.0 installed on the same machine, so it’s easy to have a transition period as you move to the new version.

# Key New Features

-   FACTS Staged Design:
    -   The simulation of one treatment selection stage followed by another.
    -   The stages can be connected on a scale from completely seamless to completely independent.
    -   FACTS Staged Design can be used to simulate:
        a)  a Phase II and the consequential Phase III trials, or a seamless Phase II/III trial
        b)  a Phase IIA and the consequential Phase IIB trials, or a seamless Phase IIA/B trial
        c)  a Phase II trial with a treatment arm selection and expansion stage
    -   The simulations include:
        a)  Different options for specifying the interval between the stages
        b)  Different options for which data from the first stage can be included in the second stage: all of it, none of it, all the data on the arms retained in the second stage, all the data on the study drug arms in the first stage pooled on the one study drug arm retained in the second stage and just subjects from the first stage who did not complete in that stage.
        c)  Rules for selecting which treatment arms are kept in the second stage or are dropped after the first stage, including rules on specific arms (such as “retain the top dose if …”), rules on specific target arms (such as “retain the Minimum Efficacious Dose which has a Hazard Ratio of X or less compared to the Control Arm”) rules across all arms (such as “retain the 2 treatment arms with the highest probability of having a response greater than control, as long as their probability of toxicity is less than …”) and rules applied to groups of treatment arms (such as “retain the two arms that are once a day treatments rather than the two that are twice a day treatments if …”).
        d)  Different analysis models, allocation rules, interims and decision criteria for each stage.
    -   The ability to take decision in Stage 1 based on the predictive probability of the outcome of stage 2.
    -   The full simulation output of both stages.
    -   Graphs of the Stage 1, Stage 2, Dose Selection and Overall results.
-   FACTS Enrichment Designs:
    -   As in FACTS Core, the scheduling of interims can now be specified by the number of subjects who have completed or have completed up to a particular visit.
    -   The decision criteria thresholds can be specified separately for different interims.
-   FACTS Core:
    -   The option to specify a deterministic accrual and/or deterministic allocation sequence, for example allowing custom dose escalation trials with cohort accrual, while allowing the full functionality of the Core engine
-   FACTS Dose Escalation:
    -   Is unchanged.

# Downloading FACTS 6.0.0

The FACTS 6.0.0 release is available for download from the Berry Consultants FACTS 6 ftp repository at http://berry1.berryconsultants.com/facts_6/.

Login using:

-   Username: facts_6
-   Password: DynIrgyur4

There are, as usual, 4 files to download: Documents.zip, Examples.zip, Setup.msi, setup.exe. Obfuscated versions of setup.exe and Setup.msi have been included for those of you accessing through firewalls that prevent the download of .exe and .msi files. Having downloaded setup.e_e and Setup.m_i simply rename the file suffix before using.

# Installing FACTS 6.0.0

As with previous version of FACTS, FACTS 6.0.0 installs on a PC. Simply place the downloaded files on the PC / laptop it is to be installed on and run the file “setup.exe”. You will need a new FACTS license key for this new version. It will be sent to you separately.

For any support questions or issues, please [contact us](../../contact.qmd).
