---
title: "FACTS 7.1.1 Release Notes"
subtitle: "April 1, 2025"
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
---

# Major Improvements

There are 4 main improvements with FACTS 7.1.1:

 - The FACTS Cloud download website has replaced the Microsoft App Center (which they are arbitrarily withdrawing from service).
 - FACTS User Guides have been moved online to the FACTS knowledge hub: [See here](../../../documentation/v71/userguides/)
 - The equations displayed on the FACTS user interface are being comprehensively overhauled so that they are clearer, more consistent and more correct. So far the main equation group of the FACTS Core, FACTS Staged and FACTS Platform Trial dose response models have been done.
 - The FACTS user interface tooltips (started in 7.1.0) have been extended to all of FACTS Core Continuous, Dichotomous and Time-to-Event. There is a setting in the Settings > Options menu command to turn them off if you don’t need them.

# Additional Improvements

## FACTS Core and Staged Improvements

- In Core and Staged designs, when recruiting subjects deterministically, specifying a deterministic accrual profile without an associated file and saving the associated design will no longer cause FACTS to close unexpectedly.
- In Core and Staged designs, the Virtual Subject longitudinal responses will handle the fraction of final SD per visit correctly when visits are deleted.
- In Core and Staged designs, global frequentist analyses will not longer be performed by default when creating new designs.
- In FACTS Core and Staged designs, the output flag specified when calling engine executables in execution mode will now correctly create the execdatasummary.csv file in the specified output directory.
- In FACTS Core and Staged designs, new designs will by default no longer perform trial level frequentist analysis calculations.
- In Staged designs, conditional power of current stage 2 when no control arm is carried to stage 2 will now be handled correctly.
- In Staged designs, the 80% percentile of the number of subjects reported in the summary results will be consistent with that displayed in Core designs.
- In Stage Multiple Endpoint designs, the sort criterion on the Transition tab will now be saved correctly when the sort criterion uses a non-primary endpoint QOI.

## FACTS Enrichment Design Improvements
- In Enrichment designs, new designs will by default no longer perform trial level frequentist analysis calculations.

## FACTS Dose Escalation Improvements
- In 2D-CRM, the default overdose control settings have been updated to match those in CRM.
- In 2D-CRM, auto generating doses will now correctly allow for dose strengths of zero.
- In 2D-CRM, the response model by default will have the eta parameter prior specified in lognormal space.

Please [contact us](../../../contact/index.qmd) regarding any questions.
