---
title: "FACTS 7.2.0 Release Notes"
subtitle: "June 30, 2025"
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
---

# Introduction

FACTS 7.2.0 is now available for download via [FACTS Cloud](https://factscloud-live.azurewebsites.net/). The highlights of the release are:

- New "non-model" (rule-based) dose escalation engines for simulating BOIN, mTPI-2 and i3+3 designs. This is a powerful feature that allows a user to now simulate all these designs in one interface to easily compare the different methods. In addition, the user can compare the results to a CRM design using the Bayesian Logistic Regression Model (BLRM).
- New "Operational" Quantities of Interest (QOIs) that can be used to take the state of the trial (such as the number of patients enrolled on the arm with the maximum response) into account in decision making.
- New graphs of the evolution of QOIs within the simulations and a quick summary graph of the results.
- New and improved landing page with updated options and example templates.

# FACTS Core and Staged Improvements

- In Core and Staged designs, users can now specify the following "Operational" QOIs in decision making criteria. For continuous/dichotomous endpoints: the number of patients enrolled, the number of patients with complete data at a specified visit, the number of patients with opportunity to complete at a specified visit and the effective dose strength. For time-to-event (TTE) endpoints: the number of patients enrolled, the number of events that have occurred, the exposure time and the effective dose strength.     
- In Core and Staged designs, users can now view on the "Per Sim: Interim Info" graph the evolution of a given Decision QOI across all interims of a given simulation, along with the outcome of that simulation and the final analysis evaluation. The evolution of the number of subjects enrolled, completers, dropouts and number of events (in TTE) is also displayed. A summmary view including the evolution of the mean Decision QOI value across all interims and the display of 100 individual simulations of the Decision QOI is also now available in the "QOIs at Interims" graph.  
- In Core and Staged designs, simulating the design's scenarios will now immediately bring up the "Across Scenarios" graphs upon completion. The default graph that will be shown will be a breakdown of trial outcomes for each simulated scenario.
- In Core and Staged designs, the weeks and simulations files will report, for each QOI category (Posterior Probability QOIs, Predictive Probabilities QOIs, p-value QOIs, target dose QOIs and Operational QOIs), the dose which has the largest (or smallest for p-value QOIs) QOI value. These will be displayed in columns whose name is "[QOI category name] Dose".
- In Core and Staged designs, designs created with FACTS 6.1 or older and loaded in FACTS 7.2 will now correctly generate frequentist output files for backward compatibility.
- In Core and Staged designs which are non-adaptive, FACTS will now correctly report the fixed randomization probabilities.
- In Core and Staged Time-to-Event designs, the default response model being used for the predictor has been changed from the three-parameter logistic model to the independent arm model.
- In Core Multiple Endpoint designs, FACTS will now correctly handling the display of QOI simulation results in the GUI when loading an existing designs.
- In Core Multiple Endpoint designs, FACTS will now correctly display the Across Scenario Receiver Operating Characteristics graph.
-	In Staged designs, the "Mirror Stage 1 Longitudinal Model in Stage 2" on the Design > Longitudinal tab will be fully visible.
- In Staged design, Stage 2 adaptive allocation now defaults to all treatments except Treatment 1 as adaptive.

# FACTS Enrichment Design Improvements

- In Enrichment designs, users can now view on the "Per Sim: Interim Info" graph the evolution of the number of subjects enrolled across all interims of a given simulation.
- In Enrichment designs, simulating the design's scenarios will now immediately bring up the "Across Scenarios" graphs upon completion. The default graph that will be shown will be a breakdown of trial outcomes for each simulated scenario.
- In Time-to-Event Enrichment designs, the VSR, Group Response Hazard ratio default values were changed from 0.9 to 1.0.

# FACTS Platform Trial Improvements
- In Platform Trial designs, users can now view on the "Per Sim: Update Info" graph the evolution of a given QOI across all interims of a given simulation. The evolution of the number of subjects enrolled, completers, dropouts is also displayed. A summmary view including the evolution of the mean Decision QOI value across all interims and the display of 100 individual simulations of the Decision QOI is also now available in the "QOIs at Updates" graph.  
- In Platform trial designs, simulating the design's scenarios will now immediately bring up the "Across Scenarios" graphs upon completion. The default graph that will be the a boxplot of the QOI values per arm for each simulated scenario.

# FACTS Dose Escalation Improvements

- A new rule-based design family is available, from which BOIN, mTPI, mTPI-2, i3+3 and 3+3 designs can all be created and seamlessly changed from one to the other. 
- In CRM and rule-based designs, simulating the design's scenarios will now immediately bring up the "Across Scenarios" graphs upon completion. The default graph that will be shown will be a breakdown of the proportion of times each dose has been declared as the MTD, for each scenario.
- In rule-based mTPI designs, cohort expansion columns present in the summary file will now be displayed as "-9999" (the N/A code) instead of empty or "0" entries when the underlying design does not have cohort expansion enabled.
- In rule-based mTPI designs, packetised simulations will now correctly display the simulation number in the resulting simulations.csv file, instead of showing duplicate simulation numbers. 
- In rule-based mTPI designs, the final selected MTD is now reported correctly in all instances.
- In rule-based mTPI designs, the "Number of addition cohorts accrued before response from current cohort is available" has been removed. Older designs with a non-zero value for this field will be set to zero when loaded in FACTS 7.2 [BREAKING CHANGE].
- In rule-based mTPI designs, the open enrollment option has been removed. Older designs that use open enrollment will be set to cohort enrollment when loaded in FACTS 7.2 [BREAKING CHANGE].
- In rule-based mTPI designs with cohort expansion, the label "Selected Post CE MTD" (the model MTD estimate after cohort expansion) will be renamed "Selected next dose after CE". 

# General Improvements

- The FACTS landing has been completely revamped. In particular, the landing page provides template designs for each trial type to help users get their particular trial design up and running faster. This is particularly useful for users new to FACTS.
- FACTS will no longer mark a simulated scenario as having errored when simulations have completed successfully but the associated temporary "pkt" simulation folders where each simulation packet is run have failed to be deleted. This can typically arise when simulating a FACTS design saved on a shared drive.
- FACTS designs simulated on a shared/remote drive such as OneDrive will be handled more robustly.
-	FACTS designs simulated using a self hosted HPC grid will now be handled in a more user-friendly way; by first checking if the HPC grid URL is correct, and by only reporting grid submission failures once all simulations have been processed to prevent job submission processing from being blocked [Enterprise licensees only].
- The FACTS "Across Scenarios" graphs have been improved to only display scenarios that have simulation results.
- FACTS will no longer display a warning message for using the "Legacy Adaptation" allocation option when the underlying design does not make use of adaptive features.

Please [contact us](../../../contact/index.qmd) regarding any questions.
