---
title: "FACTS Core Designs"
subtitle: "Overview of the capabilities of the FACTS Core Design Engine."
title-block-banner: '#125740'
title-block-banner-color: white
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: false
    number-depth: 4
---

# Scope of this User Guide

This document covers the design options that are common across the four FACTS Core Design Engines: Continuous, Dichotomous, Time-to-Event, and Multiple Endpoint. Some design elements are shared across design engines, in which case there is only a single description of them. Others differ based on the endpoint used, in which case separate pages have been created to describe each.

The screenshots provided are specific to a particular installation and [may not reflect the exact layout](## "Screenshots from earlier versions of FACTS 6 are retained only where they are unchanged in FACTS 7.1") of the information seen by any particular user. They were taken from FACTS V7 & V6 installed on Windows 10 or 11. If FACTS is installed on different versions of Windows, or with different Windows ‘themes’ there will be some differences in appearance introduced by Windows. The contents of each tab, however, will generally be consistent with the screenshots in this document.

## FACTS Version

This is the version of the user guide for inclusion with the FACTS 7.1 release.

## Citing FACTS

Please cite FACTS wherever applicable using [this citation](../../../../introduction/citation.qmd).

# FACTS Core Overview

FACTS Core is generally used to simulate trials where one or more active arms
are compared to a common control arm. Examples of trials that can be simulated
in FACTS Core engines are: Group sequential designs, goldilocks designs, dose-
finding phase 2 designs, fixed phase 3 designs, arm dropping designs, response
adaptive allocation designs, and more.

FACTS Core can be frequentist or bayesian, and as adaptive as needed or fixed,
and not adaptive at all.

FACTS provides numerous options for the statistical analysis, some of
them straight forward, some of them quite novel, though all have been
used in actual trials:

-   The endpoint can be continuous, dichotomous, or time to event. Multiple
    continuous/dichotomous endpoints can be simulated in 1 trial.

-   As well as a control arm, the study arms can be compared with an
    active comparator.

-   When simulations are executed, they can be executed for a wide range of
    scenarios. A scenario can be composed of a combination of one of each
    type of profile – dose response, longitudinal, accrual, and dropout.

-   With either a dichotomous or continuous endpoint, longitudinal
    models can used to impute the patient’s likely final outcome from
    early interim measures. This can be used when final endpoint data is
    missing due to subject drop-out or at interims for subjects who’ve
    not reached their final endpoint yet.

-   Estimation of the response on the control arm can be augmented using
    a hierarchical model to borrow from data from previous studies (This
    is known as Bayesian Augmented Control, BAC).

-   Interim analyses can be specified at fixed intervals by time, the number of
    subjects recruited, or the number of events observed.

-   At interim analyses, options include:

    -   Choosing to stop the whole study for success or futility.

    -   Dropping treatment arms

    -   Adapting the randomization proportions to favor allocating to
        the doses that are most likely to be the desired target – which
        can be the study arm with the maximum response, the EDx, or
        minimum efficacious dose.

The main tabs in FACTS:

The Study Tab
: The Study Tab is used for entering the main characteristics of the
study and specifying the treatment arms to be tested in the study.
This is where the user specifies the 'given' requirements, or
constraints, of the trial to be designed.

Virtual Subject Response
: The VSR tabs are for specifying the simulation
of subject responses. This is either by specifying assumed efficacy scenarios
for each treatment arm, or by supplying external data files
of simulated subject responses.

Execution
: The Execution tab is for specifying operational properties of the trial's
execution to simulate. Specifically, the rate of subject accrual and
the probability of subjects dropping out.

Quantities of Interest
: The Quantities of Interest tab is for specifying the quantities to
be calculated during analyses for output in the results, and
possible use in adaptive allocation, early stopping and final
evaluation decisions.

Design
: The Design tabs are for specifying the statistical analysis and adaptive
design rules. These are the design choices available to the trial
biostatistician and include how to model the final responses, allocation rules,
missing or unobserved data handling, what decisions to
make at interims, and how to determine if the overall trial has been
successful.

Simulation
: The simulation tab is for the user to set up and run simulations. It also
allows for viewing of the simulation results either as output simulation files
or pre-made graphics that provide many summaries of the simulation outcomes.

Analysis
: On the Analysis tab, the user can load an example data set and view
the results of the FACTS analysis of that data using the current
specified design. This tab is useful for implementation of a design that was
simulated in FACTS.

Each of the above tabs also has sub-tabs that help with configuring the
