---
title: "How to Cite"
subtitle: "Most common Citation Styles for both FACTS and the Knowledge Hub"
title-block-banner: '#125740'
title-block-banner-color: white
format:
  html:
    code-copy: true
csl: ieee.csl
---

# FACTS Software

Please cite FACTS when you are writing papers or preparing slides for which you have used FACTS. The correct way to cite FACTS is to include the FACTS software version number in the text and then point to the full reference, like so: *We used FACTS 7.1 [@FACTS] to simulate the trial*.  Here are the most common citation formats:

::: {.panel-tabset}

## APA 

```{R, echo = FALSE, results = 'asis'}
year <- format(Sys.Date(), "%Y")
ref_APA <- paste0(
  "FACTS Development Team. (", year, "). ",
  "FACTS: Fixed and Adaptive Clinical Trial Simulator [Computer software]. ",
  "Berry Consultants LLC, Austin, TX, USA. ",
  "https://www.berryconsultants.com/software/facts/"
)
cat("```bibtex\n", ref_APA, "\n```", sep = "")
```

## MLA

```{R, echo = FALSE, results = 'asis'}
year <- format(Sys.Date(), "%Y")
date_MLA <- format(Sys.Date(), "%d %b. %Y")
ref_MLA <- paste0(
  "FACTS Development Team. FACTS: Fixed and Adaptive Clinical Trial Simulator. ",
  "Berry Consultants LLC, ", year, ", ",
  "https://www.berryconsultants.com/software/facts/. Accessed ", date_MLA, "."
)
cat("```bibtex\n", ref_MLA, "\n```", sep = "")
```

## Chicago

```{R, echo = FALSE, results = 'asis'}
year <- format(Sys.Date(), "%Y")
date_Chicago <- format(Sys.Date(), "%B %d, %Y")
ref_Chicago <- paste0(
  "FACTS Development Team. ", year, ". ",
  "FACTS: Fixed and Adaptive Clinical Trial Simulator [Computer software]. ",
  "Austin, TX: Berry Consultants LLC. ",
  "https://www.berryconsultants.com/software/facts/ (accessed ", date_Chicago, ")."
)
cat("```bibtex\n", ref_Chicago, "\n```", sep = "")
```

## Harvard

```{R, echo = FALSE, results = 'asis'}
year <- format(Sys.Date(), "%Y")
date_Harvard <- format(Sys.Date(), "%d %B %Y") 
ref_Harvard <- paste0(
  "FACTS Development Team, ", year, ". ",
  "FACTS: Fixed and Adaptive Clinical Trial Simulator [Computer software]. ",
  "Austin, TX: Berry Consultants LLC. Available at: <https://www.berryconsultants.com/software/facts/> ",
  "(Accessed: ", date_Harvard, ")."
)
cat("```bibtex\n", ref_Harvard, "\n```", sep = "")
```

## Vancouver

```{R, echo = FALSE, results = 'asis'}
year <- format(Sys.Date(), "%Y")
date_Vancouver <- format(Sys.Date(), "%Y %b %d")
ref_Vancouver <- paste0(
  "FACTS Development Team. FACTS: Fixed and Adaptive Clinical Trial Simulator [Computer software]. ",
  "Austin, TX: Berry Consultants LLC; ", year, ". Available from: https://www.berryconsultants.com/software/facts/ ",
  "[cited ", date_Vancouver, "]."
)
cat("```bibtex\n", ref_Vancouver, "\n```", sep = "")
```

## BibTex

```{R, echo = FALSE, results = 'asis'}
year <- format(Sys.Date(), "%Y")
ref <- paste0(
 "@Manual{FACTS,", "\n",
    "title = {{FACTS: Fixed and Adaptive Clinical Trial Simulator}},", "\n",
    "author = {{FACTS Development Team}},", "\n",
    "organization = {{Berry Consultants LLC}},", "\n",
    "type = {Computer Software},", "\n",
    "address = {Austin, TX, USA},", "\n",
    "year = {", year, "},", "\n",
    "note = {https://www.berryconsultants.com/software/facts/}", "\n",
 "}"
)
cat("```bibtex\n", ref, "\n```", sep = "")
```

## BibLaTex

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
ref_biblatex <- paste0(
 "@Manual{FACTS,", "\n",
    "title = {{FACTS: Fixed and Adaptive Clinical Trial Simulator}},", "\n",
    "author = {{FACTS Development Team}},", "\n",
    "organization = {{Berry Consultants LLC}},", "\n",
    "type = {Computer Software},", "\n",
    "address = {Austin, TX, USA},", "\n",
    "year = {", year, "},", "\n",
    "url = {https://www.berryconsultants.com/software/facts/}", "\n",
 "}"
)
cat("```bibtex\n", ref_biblatex, "\n```", sep = "")
```


:::


# Pages on the FACTS Knowledge Hub

Please cite the FACTS Knowledge Hub when you are writing papers or preparing slides for which you have used the FACTS Knowledge Hub. The correct way to cite the FACTS Knowledge Hub is to include *FACTS Knowledge Hub* in the text and then point to the full reference, giving the date when the webpage was accessed, like so: *For more information on Time Course Hierarchical Longitudinal Models, see the FACTS Knowledge Hub [@FACTSKH]*. Here are the most common citation formats using the above example (please substitute the title and link with the actual page you want to cite):

::: {.panel-tabset}

## APA 

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
date_APA <- format(Sys.Date(), "%B %d, %Y") 
ref_APA <- paste0(
  "Berry Consultants LLC. (", year, "). Longitudinal Models for Continuous Endpoints. ",
  "Retrieved ", date_APA, ", from https://docs.berryconsultants.com/documentation/v71/userguides/core/longitudinalmodels/continuous.html"
)
cat("```bibtex\n", ref_APA, "\n```", sep = "")
```

## MLA

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
date_MLA <- format(Sys.Date(), "%d %b. %Y") 
ref_MLA <- paste0(
  "Berry Consultants LLC. Longitudinal Models for Continuous Endpoints. ", year, 
  ", https://docs.berryconsultants.com/documentation/v71/userguides/core/longitudinalmodels/continuous.html. Accessed ", date_MLA, "."
)
cat("```bibtex\n", ref_MLA, "\n```", sep = "")
```

## Chicago

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
date_Chicago <- format(Sys.Date(), "%B %d, %Y")
ref_Chicago <- paste0(
  "Berry Consultants LLC. ", year, ". Longitudinal Models for Continuous Endpoints. ",
  "https://docs.berryconsultants.com/documentation/v71/userguides/core/longitudinalmodels/continuous.html (accessed ", date_Chicago, ")."
)
cat("```bibtex\n", ref_Chicago, "\n```", sep = "")
```

## Harvard

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
date_Harvard <- format(Sys.Date(), "%d %B %Y")
ref_Harvard <- paste0(
  "Berry Consultants LLC, ", year, ". Longitudinal Models for Continuous Endpoints. [online] ",
  "Available at: <https://docs.berryconsultants.com/documentation/v71/userguides/core/longitudinalmodels/continuous.html> [Accessed ", date_Harvard, "]."
)
cat("```bibtex\n", ref_Harvard, "\n```", sep = "")
```

## Vancouver

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
date_Vancouver <- format(Sys.Date(), "%Y %b %d")
ref_Vancouver <- paste0(
  "Berry Consultants LLC. Longitudinal Models for Continuous Endpoints [Internet]. ",
  year, " [cited ", date_Vancouver, "]. Available from: https://docs.berryconsultants.com/documentation/v71/userguides/core/longitudinalmodels/continuous.html"
)
cat("```bibtex\n", ref_Vancouver, "\n```", sep = "")
```

## BibTex

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
date <- format(Sys.Date(), "%Y-%m-%d")
ref <- paste0(
 "@misc{FACTSKH,", "\n",
    "title = {{Longitudinal Models for Continuous Endpoints}},", "\n",
    "author = {{Berry Consultants LLC}},", "\n",
    "year = {", year, "},", "\n",
    "howpublished = {\\url{https://docs.berryconsultants.com/documentation/v71/userguides/core/longitudinalmodels/continuous.html}},", "\n",
    "note = {[Online; accessed ", date, "]},", "\n",
 "}"
)
cat("```bibtex\n", ref, "\n```", sep = "")
```

## BibLaTex

```{R, echo = FALSE, results='asis'}
year <- format(Sys.Date(), "%Y")
date <- format(Sys.Date(), "%Y-%m-%d")
ref_biblatex <- paste0(
 "@online{FACTSKH,", "\n",
    "title = {{Longitudinal Models for Continuous Endpoints}},", "\n",
    "author = {{Berry Consultants LLC}},", "\n",
    "year = {", year, "},", "\n",
    "url   = {https://docs.berryconsultants.com/documentation/v71/userguides/core/longitudinalmodels/continuous.html},", "\n",
    "urldate = {", date, "},", "\n",
 "}"
)
cat("```bibtex\n", ref_biblatex, "\n```", sep = "")
```

:::