---
title: "Introduction"
subtitle: "Get Started and Build Your Foundation"
---

Welcome to the Introduction section — your starting point for learning how you can use FACTS to set yourself up for success. Here, you’ll find everything you need to understand the fundamentals of our software, from step-by-step tutorials and guided walkthroughs to links to relevant webinars and other community resources.

## What You’ll Find Here

- Getting Started: Begin with the fundamentals. Understand the initial setup steps, basic navigation, and how to configure the product to meet your needs.
- Webinars: Explore in-depth demonstrations led by our experts. Gain clarity on complex features, see best practices in action, and deepen your product knowledge with real-time guidance.
- Tutorials: Learn how key functionalities work and discover creative ways to integrate them into your workflows. See how other teams and users are leveraging the product to achieve their goals.

## How to Use This Section

Whether you’re a prospective client, brand new to FACTS or brushing up on fundamentals, this Introduction area is designed to help you gain confidence with FACTS. Start by reviewing the fundamentals, watch a webinar to see the product in action, and use the resources provided to support your ongoing growth. We’re here to ensure you have a smooth and rewarding learning experience. If you have any questions, don't hesitate to [contact us](../contact.qmd). 
