---
title: "Videos and Webinars"
subtitle: "Complete List of Online Video Resources for FACTS"
title-block-banner: '#125740'
title-block-banner-color: white
---

## Introductions
- [Introduction to FACTS](https://www.youtube.com/watch?v=SZfCz9JKxv8)
- [Dose Escalation N-CRM Example](https://www.youtube.com/watch?v=HWB6sR1nZGo)
- [Core Dichotomous Simple Two-Arms Example](https://www.youtube.com/watch?v=D2SvWZuPy5Y)
- [Enrichment Designs: Basket Trial Example](https://www.youtube.com/watch?v=9X4AulAk4M8)
- [FACTS Platform Trial Intro](https://www.youtube.com/watch?v=-SUmMjHg130)

## Training Sessions
- [FACTS Core Introduction](https://bit.ly/30HzpkC)
- [FACTS Core Dose Response Models](https://bit.ly/32qcxa4)
- [FACTS Core Predictive Probabilities](https://bit.ly/3FfNYLq)
- [FACTS Core Arm Dropping and RAR](https://bit.ly/3eaU6IY)
- [FACTS Core Multiple Endpoint](https://bit.ly/3mlWa5d)
- [FACTS Core and Enrichment Designs Longitudinal Modeling](https://bit.ly/3eajKxs)
- [FACTS Core Time-to-Event](https://bit.ly/32kSiu4)
- [FACTS Core Time-to-Event Predictors](https://bit.ly/3yHLsuO)
- [FACTS Enrichment Designs Introduction](https://bit.ly/3GQf2RQ)
- [FACTS Enrichment Designs Hierarchical Modeling](https://bit.ly/3efX3I1)
- [FACTS Enrichment Designs Borrowing information on control](https://bit.ly/3qbAzOf)
- [FACTS Core and Enrichment Designs Hierarchical Prior for Control](https://bit.ly/3ecqCKN)
- [FACTS Dose Escalation Introduction](https://bit.ly/3J4BnNg)
- [FACTS Dose Escalation N-CRM Setting the Prior](https://bit.ly/3yHMA1w)
- [FACTS Dose Escalation N-CRM Open enrollment, pseudo subjects, expansion cohort, fine spaced doses](https://bit.ly/3qdYVqA)
- [FACTS Dose Escalation N-CRM Ordinal toxicity, 2 samples, efficacy](https://bit.ly/3pdmKzB)
- [FACTS Dose Escalation 2D-CRM](https://bit.ly/33A5xHY)
- [FACTS Staged Design Introduction](https://bit.ly/3qaIM56)
- [FACTS Staged Design First Example](https://bit.ly/32aO4Wc)
- [FACTS Staged Design Advanced Topics](https://bit.ly/3qbD6bd)
- [FACTS Dose Escalation - Hands On Training](https://bit.ly/30I91Hm)
- [FACTS Staged Design - Hands on Training](https://bit.ly/3paDRC2)

## Introduction to Adaptive Design Using FACTS Webinar Series
- [Phase 1 Dose Escalation](https://youtu.be/QfodSEPUGUM&t)
- [Arm Dropping and RAR](https://youtu.be/nPXb-CuMY9s)
- [Basket Trials](https://youtu.be/k88VRMZAgIg)
- [Group Sequential](https://youtu.be/BQfy_ne-GeQ&t)
- [MAMS and Platform Trials](https://youtu.be/dRf79rbWoyA)
- [Seamless Phase 2-3](https://youtu.be/OzXyHcD1GBE)

## Introductory Topics
- [The Uses of Trial Simulation in Consulting](https://youtu.be/nWPuFWnwKM8)
- [FACTS Core Design Exploration - part 1](https://youtu.be/N2ciqsM-gSA)
- [FACTS Core Design Exploration - part 2](https://youtu.be/oz3FUU2qqrQ)
- [Stopping for Futility](https://youtu.be/rjmMt-RYv2w)
- [N-CRM Case Study](https://youtu.be/dPb5wb9Z6ko)
- [Introduction to Staged Designs](https://youtu.be/VqnTsgq1nkA)

### Discussion of FDA Guidance
- [Discussion of the new FDA Guidance on Adaptive Designs](https://youtu.be/3KOjdhG_7VM)

## Response Adaptive Randomization
- [The pros and cons of Response Adaptive Randomization (RAR)](https://youtu.be/PqVfqU3IdMI)
- [RAR and arm dropping in FACTS](https://youtu.be/dJ8IPiyLWMk)
- [Adaptive Randomization Works](https://youtu.be/f3dZneMTwvY)
- [Response Adaptive Randomization (RAR) in multi-arm trials seeking to find the best arm](https://youtu.be/v5V5Y3wTNx8)

## Case Studies
- [The Evolution of a trial from FACTS Core to Staged Design and back](https://youtu.be/KeJpNOTHE9k)
- [Using a biomarker endpoint to trigger phase 3](https://youtu.be/UxlA2iTZVLQ)
- [Designing an Adaptive Multiple Dose Trial with FACTS](https://youtu.be/7O7rvZEvGmo)
- [Papers on Bayesian Group Sequential Designs](https://youtu.be/VFRbpxxiOJI)
- [The ENRICH trial an Enrichment Design case study](https://youtu.be/H6tkrjJzP64)
- [The ENRICH Trial re-visited](https://youtu.be/wr_twHSOSmY)
- [A seamless phase 2/3 trial in type-2 diabetes](https://youtu.be/Ot1ACLRuJaI)
- [A two arm study with adherence model driven effect size and irregular interims](https://youtu.be/pGsti-Pj2qI)
- [A Phase 1 dose escalation study using open enrolment](https://youtu.be/nt_1nJkEz5U)
- [A successful dose finding study in Alzheimer's](https://youtu.be/9pmRCtbrYfQ)
- [A two arm non-inferiority MACE safety study](https://youtu.be/rccuslJekH8)

## Advanced Topics
- [Calibrating hierarchical model priors](https://youtu.be/cu5esx9YIRs)
- [Post Processing FACTS output with R](https://youtu.be/EmEyEXVrthM)
- [Using FACTS to analyze Ordinal Data](https://youtu.be/nKHn6XCo23w)
- [FACTS predictive Power and Predicting the Trial Outcomes](https://youtu.be/E7o0W2Dxmr8)
- [Dose escalation designs with open enrollment](https://youtu.be/40hIbQkKzEk)
- [FACTS Core TTE Predictors](https://youtu.be/Z9iU0YHoqn8)
- [Early decision making PFS and OS - part 1](https://youtu.be/J0pRAZk0x90)
- [Early decision making PFS and OS - part 2](https://youtu.be/Km6UcHvgM9E)

## Optimization
- [Phase 2 sources of efficiency](https://youtu.be/kMNS7nG9GAU)
- [Picking the Winner - how to compare trial designs](https://youtu.be/HLvNgWYT5U0)
- [An early look at QUOTES and Estimating eNPV](https://youtu.be/PnqSX2-YjEU)
- [Applying Bayesian Optimization to FACTS Trial designs and choosing stopping boundaries](https://youtu.be/P2qpfJTkCcc)
- [Trial Design Optimization through the lens of expected Net Present Value](https://youtu.be/M5sDsJFu8cM)
