---
title: "FACTS 7.1.1 Release Notes"
subtitle: "XX XX, 2025"
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
---

# Introduction

# FACTS Core and Staged Improvements

- In Core and Staged designs, when recruiting subjects deterministically, specifying a deterministic accrual profile without an associated file and saving the associated design will no longer cause FACTS to close unexpectedly.
- In Core and Staged designs, the Virtual Subject longitudinal responses will handle the fraction of final SD per visit correctly when visits are deleted.
- In Core and Staged designs, global frequentist analyses will not longer be performed by default when creating new designs.
- In FACTS Core and Staged designs, the output flag specified when calling engine executables in execution mode will now correctly create the execdatasummary.csv file in the specified output directory.
- In FACTS Core and Staged designs, new designs will by default no longer perform trial level frequentist analysis calculations.
- In Staged designs, conditional power of current stage 2 when no control arm is carried to stage 2 will now be handled correctly.
- In Staged designs, the 80% percentile of the number of subjects reported in the summary results will be consistent with that displayed in Core designs.

# FACTS Enrichment Design Improvements
- In Enrichment designs, new designs will by default no longer perform trial level frequentist analysis calculations. 

# FACTS Dose Escalation Improvements
- In 2D-CRM, the default overdose control settings have been updated to match those in CRM.
- In 2D-CRM, auto generating doses will now correctly allow for dose strengths of zero.
- In 2D-CRM, the response model by default will have the eta parameter prior specified in lognormal space.