---
title: "FACTS 7.0.0 Release Notes"
subtitle: "April 5, 2023"
bibliography: ../../references.bib
format: 
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    number-sections: true
    number-depth: 3
    css: ../../styles.css
---

# Introduction

FACTS 7.0.0 is now available for download via App Center. This release marks the addition of two new FACTS design types: Platform Trial Design – Continuous and Platform Trial Design – Dichotomous.

Please [contact us](../../individualPages/contact.qmd) regarding any questions.

# FACTS Platform Trial Features

Within these new Platform Trial design types, FACTS users can now:

-   Simulate a platform trial, for a continuous/dichotomous endpoint, with various trial level participant and arm constraints. In particular, users can specify a maximum enrollment time, number of participants, successful treatments, participants per arm and concurrent treatments.
-   Simulate a platform trial with treatments arriving at different times during the trial.
-   Specify simulated mean arm responses/effects to be a fixed value or sampled from a distribution.
-   Simulate participant accrual, responses, and dropout rates as per FACTS Core.
-   Specify a constant proportion of participants allocated to the control arm, or an allocation dependent on the number of treatments currently in the trial, with the option of performing response adaptive randomization.
-   Analyze participant data and estimate mean treatment responses using a Bayesian independent arm model, or frequentist p-values, comparing treatment arms to a common control arm.
-   Specify “Trial Update” information and frequency, at which analyses are performed and allocation ratios may get updated.
-   Specify when to evaluate “Treatment Milestones”, at which decisions are made about treatment outcomes.
-   Specify success/futility criteria that apply to all treatments, or to specific treatments.
-   Classify treatments as Good, Mediocre or Unacceptable to get summary statistics such as the proportion of ‘Good’ treatments that are successful/inconclusive/unsuccessful and similarly for the other classifications.
-   View granular simulation and summary results of various Platform Trial operating characteristics.
-   Generate a Platform Trial design report outlining the characteristics of the simulated design in a Word document.

# FACTS Core and Staged Improvements

-   In FACTS Core and Staged designs (except Time-to-Event designs), users can now simulate single arm trials, with options for both Bayesian and Frequentist p-values to be calculated comparing the data on the experimental arm to an objective reference response/response rate specified on the QOI tab.
-   FACTS Core and Staged designs (except Time-to-Event designs) will now correctly handle frequentist calculations when a control arm is not present and comparison is performed against an objective reference response/response rate.
-   p-value calculations have been updated to better accommodate their use at interims, with dropouts and incomplete subjects now handled differently. No incomplete subjects have a final endpoint imputed, but subjects that are known dropouts and have had the opportunity to complete are imputed/ignored according to the "Handle missingness" option for the p-value.
-   LOCF behavior has been made consistent. LOCF will impute a participant’s baseline value as their final outcome if a baseline value is observed and no non-baseline visit data is observed.
-   FACTS Staged designs will now correctly handle the mirroring of Stage 1 data in Stage 2 for the Dose Response and Longitudinal models.

# FACTS Enrichment Design Improvements

-   In FACTS Enrichment Time-to-Event designs, FACTS will now correctly apply the user specified alpha levels per group when calculating frequentist output summaries.
-   In FACTS Enrichment Time-to-Event designs, FACTS will now correctly calculate frequentist output when the underlying design has only specified one group.
-   In FACTS Enrichment designs, FACTS will now enforce group caps to be strictly greater than zero.

# FACTS Dose Escalation Improvements

-   On the Analysis tab, FACTS will now enforce the specification of the cohort number when uploading a subject data file to run an analysis.
-   In 2D-CRM, FACTS will now correctly handle a rare situation in the row-by-row run-in scheme.
-   In 2D-CRM, the engines when run in a Linux environment will have a correctly formatted simulation results output header.

# General Improvements

-   BREAKING CHANGE: FACTS will now consistently handle the “Date” column in a patients file to be in weeks rather than days, making it consistent with the rest of FACTS. “Patients” files generated from FACTS simulations will report the “Date” column as “DateInWeeks” to avoid any ambiguity.
-   BREAKING CHANGE: The “Date” column in Deterministic Accrual external data files will need to be manually updated to specify the date in weeks rather than days.
-   BREAKING CHANGE: The “Date” column in subject data file provided when running a FACTS Analysis will need to be updated to specify the date in weeks rather than days. If performing FACTS Analysis via the GUI, the FACTS Analysis tab provides a “Convert Date from Days to Weeks” utility that does the conversion.
-   The precision of results output in FACTS will now consistently be up to 6 decimal places for all design types, except for Time-to-Event designs which will display output up to 8 decimal places.
-   FACTS will now correctly handle interactions with the latest version of RStudio to date (2023.03.0). This includes the generation of design reports and the importing of FACTS results output to RStudio via the “Open in R” button on the Simulation tab. Note that FACTS will continue to support older version of RStudio.
