---
title: "Adaptive Trials"
format: 
  html:
    toc: true
---

## What is an Adaptive Trial?

To understand adaptive trials it may be easiest to look at a fixed trial. Traditionally a fixed sample size is specified with fixed allocation and fixed entry criteria. The data is not analyzed until trial completion, which is typically years after the trial began.  This 75-year-old design approach creates very restrictive design types – and really forces the design team to guess at the doses, range, patient population, duration and frequency of treatment, etc, because a fixed design requires linear effort spent for each treatment arm.

An adaptive trial is like driving with your eyes open! It allows the pre-specification of flexible components to the major aspects of the trial, like the treatment arms used (dose, frequency, duration, combinations, etc), the allocation to the different treatment arms, the patient population used, and the sample size. An adaptive design can learn from the accruing data what the most therapeutic doses or arms are, allowing the design to hone in on the best arms. This allows the design to start with a wider range of doses – say 8 instead of 3 – with using a smaller number of patients. The result is a smart design, using resources (including time) much more efficiently, at the same time increasing the scientific precision.  Well constructed adaptive designs can be better for all involved – better learning, more efficient, better treatment for subject in a trial, better information for regulators and the medical community.

The one drawback is that adaptive designs are more work to construct. It involves clinical trial simulation to make sure the design works well, meets regulatory scrutiny and is efficient. Creating an adaptive design means getting all parties involved in the process – having statisticians work with clinicians, marketing, regulatory experts, execution teams, drug supply, etc, to construct a highly efficient design.

Adaptive Designs are not restricted to phase I, but rather all stages of development of drugs and devices. The following list of phases/stages is where we have constructed adaptive designs:

**Phase I**:  Sample size, Dose escalation, Combination of arms, Seamless phase I-II.

**Phase II/Pilot**:  Sample size, Dose allocation, Introduce/Drop arms, Histology investigation, Prediction of Phase III, Seamless Phase II-III.

**Phase III/Confirmatory**:  Sample size, Multiple arms, Accrual Interim Analysis, Futility Analyses, Timing of Conclusions.

**Phase IV**:  Sample size, Timing of Conclusions, Indications