---
title: "Platform Trials"
format: 
  html:
    toc: true
---

## Overview

A traditional trial typically takes two years to design, create the infrastructure, and begin enrolling patients. One therapy and a control are enrolled and then the trial is over, and all the infrastructure built for the trial is obsolete and the trial addressed a single question. A platform trial is built, with a master protocol, to allow multiple therapies to be investigated in the single trial, being added continuously, all with shared infrastructure. A platform trial allows multiple arms to share a common control, share the common infrastructure of the trial, and it allows the better treatment of patients in the trial. The platform trial is a win-win for all stakeholders – smaller sample size, reduced patients on placebo, reduced costs, reduced timelines, and better inferences for regulators.

## Our experience

Scientists from Berry Consultants are internationally renowned leaders in the creation, design, and implementation of adaptive platform trials. Platform trials designed by the team at Berry Consultants are either ongoing or being initiated in oncology, infectious diseases, pulmonary and critical care, neurology, and several rare diseases. In addition, the statisticians from Berry Consultants have extensive experience working with clinical investigators and scientific domain experts in both academic and for-profit settings.

Berry Consultants has been involved in the design and implementation of the following Adaptive Platform Trials:

- [Healey ALS Platform Trial (ALS)](https://www.massgeneral.org/neurology/als/research/platform-trial)
- [iSpy-2 (Breast Cancer)](https://www.businesswire.com/news/home/20220804005949/en/Berry-Consultants-Transitioning-from-I-SPY-Trials)
- [DIAN-TU (Alzheimer’s Disease)](https://dian.wustl.edu/our-research/clinical-trial/)
- [IMI-EPAD (Alzheimer’s Disease)](https://ep-ad.org/)
- [Precision Promise (Pancreatic Cancer)](https://www.pancan.org/research/precision-promise/)
- [GBM-AGILE (Glioblastoma Multiforme)](https://www.gcaresearch.org/gbm-agile/)
- [ACTIV-4, REMAP-CAP, PRINCIPLE, DNDi ANTICOV (COVID-19 adaptive platform trials)](https://www.remapcap.org/coronavirus)
- [ARLG ADAPT (Antibiotics for Drug Resistant Infections)](https://arlg.org/adapt/)
- [PREPARE REMAP-CAP (Community Acquired Pneumonia)](https://www.remapcap.org/)
- [PREPARE-ALIC4E (Influenza)](https://www.prepare-europe.eu/about-us/workpackages/workpackage-4)
- [EBOLA (Gates Foundation Funded Platform)](https://pubmed.ncbi.nlm.nih.gov/26768569/)


If you have a need for a platform trial or would like to learn more about its benefits, please [contact us](../../contact/index.qmd).