---
title: "Longitudinal (predictor) Models for Time-to-event Endpoints"
subtitle: "Description of the predictor models for time to event endpoints."
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: false
    number-depth: 4
---

For all predictors ($Z$) for time-to-event endpoints, the engine estimates
both a marginal distribution (normal mean and variance for continuous,
probability of response for dichotomous, and a piecewise exponential
hazard model for time to event predictors) and a working model relating
the predictor to the final endpoint. The marginal distribution is used
to impute predictors for subjects lacking an observed predictor value
and may also be used for stopping (see section on stopping). The working
model is used to impute final endpoints for subjects lacking a final
endpoint. For subject missing both a predictor and final endpoint, the
predictor is imputed first from its marginal distribution, and then the
final endpoint is imputed conditionally on the predictor $Z$.

# Continuous Predictor

Within each dose (including control and active comparator), the marginal
distribution of $Z$ is a normal distribution with mean $\theta_{Zd}$ and standard deviation $\sigma_Z$. The
standard deviation is common across the doses, but the means
$\theta_{Zd}$ are allowed to vary across the same range of dose
response models as the final endpoint (NDLM, Logistic, etc.). The prior
specification for these predictor dose response models is identical in
structure to the final endpoint, although the user selects a separate
set of parameter values. The dose response for the predictor does not
need to match the dose response for the final endpoint.

The working model assumes the final event time T is related to the
predictor $Z$ by assuming $T\mid Z \sim \text{Exp}(\lambda_d e^{\beta Z})$, where
$\lambda_d$ varies by dose and has separate priors
$\lambda_d \sim \text{Gamma}(\alpha_d, \beta_d)$
for each dose. The coefficient in the exponent $\beta$ (no subscript) is
constant across doses with prior $\beta \sim \text{N}(m, s)$. 

# Dichotomous Predictor

A dichotomous predictor is handled similarly to a continuous predictor,
with a marginal distribution having a predictor dose response model.
However, in this case the predictor dose response relates the log-odds
rather than the probability of response itself. The working model for
dichotomous is identical to the working model for a continuous
predictor, with $$T\mid Z \sim \text{Exp}(\lambda_d e^{\beta Z})$$. In this
situation the working model is simpler to understand, as
$$T\mid (Z=0) \sim \text{Exp}(\lambda_d)$$ and $$T \mid (Z=1) \sim Exp(\lambda_{d\beta})$$.

# Time to Event Predictor

The time to event predictor is qualitatively different than the
continuous or dichotomous predictors. Instead of the predictor adjusting
the hazard, the time to event predictor is viewed as an offset. The
final endpoint is viewed as a sum of a predictor time $Z_1$ and a post-predictor time $Z_2$, where $Z_1$ and
$Z_2$ are independent random variables and the final endpoint
is thus $Z_1 + Z_2$.

For the working model, $Z_1 \sim \text{PWExp}(\lambda_{1s}*\theta_{1d})$ and $Z_2 \sim \text{Exp}(\lambda_{2d})$, with priors
$\theta_{1s} \sim \text{Gamma}(\alpha_{1s}, \beta_{1s})}$, $\theta_{2d} \sim \text{Gamma}(\alpha_{2d}, \beta_{2d})$
(with $Z_1$’s control hazard model potentially being piecewise
exponential). For imputation, a subject missing both the biomarker and
final endpoint times has both $Z_1$ and $Z_2$
imputed, with the final endpoint imputed as the sum. For a subject with
a predictor time but no final endpoint, $Z_2$ is imputed and
added to the observed predictor time to impute the final endpoint.
