---
title: "FACTS Rule-Based Dose Escalation"
subtitle: "3+3 / mTPI"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: true
    number-depth: 4
---

#  1 Introduction

## Purpose of this document

This document describes how to install and use the Rule-Based Dose Escalation (DE)
Fixed and Adaptive Clinical Trial Simulator (FACTS) software (from now on referred to as *Dose Escalation Fixed and Adaptive Clinical Trial Simulator Software*). It is
intended for all end users of the system.

## Scope of this document

This document covers the Dose Escalation Fixed and Adaptive Clinical
Trial Simulator Software by describing the user interface. It covers the
3+3 and mTPI. It does not cover the CRM design engine which has [its own User Guide](crm.qmd).

This document does not address the internal workings of the design
engines or algorithms, which are addressed in the associated Design
Engine Specification. It also does not address the use of FACTS Core
Designs or Enrichment Designs, which are covered in other User Guides.

The screenshots provided are specific to a particular installation and
may not reflect the exact layout of the information seen by any
particular user. They were taken from FACTS, 5 or later if changed,
installed on Windows 7 and Windows 10. Different versions of Windows or
the use of different Windows themes will introduce some differences in
appearance. The contents of each tab, however, will be consistent with
the software.

## Context of this Issue 

This document is a guide to the version 7.1 release of Dose Escalation
FACTS.

There have been no changes to these elements of FACTS since FACTS 6.1.

## Citing FACTS

Please cite FACTS wherever applicable using [this citation](../../../introduction/citation.qmd). 

## Definition of Terms

An overview of the acronyms and abbreviations used in this document can be found [here](../glossary.qmd).
