
---
title: "Virtual Subject Response"
subtitle: "Overview of the virtual subject response tab. Individual endpoint types are described separately."
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: true
    number-depth: 4
---

The Virtual Subject Response (VSR) tab allows the user to explicitly define virtual subject response profiles that dictate the distribution that patients' endpoints should be simulated from. VSRs can be specified explicitly by specifying the control distribution and treatment effects, or by importing externally simulated patient responses.

If specifying the VSR in the "Explicitly Defined" tab you will always have the
dose response VSR to specify, and if subjects have multiple visits, then a
Longitudinal VSR must be specified as well. If using a continuous endpoint and
simulating a baseline, then a baseline simulation VSR must be specified as well.

A dose response VSR specifies how all arms in the study should have their
final endpoint value simulated. For continuous endpoints this is the mean and
standard deviation of the normal distribution. For dichotomous endpoints it
is the probability of response, and for time-to-event endpoints it is the
hazard rate for each arm.

The longitudinal VSR dictates how subject visits are correlated with the final
endpoint value. Each endpoint type has different methods of simulating longitudinal
correlation, which are explained in detail in the following sections.

It is common, and advisable, to create a variety of VSR scenarios. Each
scenario is a combination of a dose response VSR, a longitudinal VSR (if it exists),
and a baseline VSR (if it exists). Generally, at least
one null VSR, and a set of alternative scenarios are created. In a null scenario
the treatment arms have the [same efficacy](## "For a superiority study. In
a non-inferiority study the treatment arms will have an efficacy profile that
lies on the control minus the non-inferiority margin.") profile as the control arm.
[Alternative](## "This term (and the term 'null scenario') is borrowed from hypothesis testing. It indicates that the
assumed scenario belongs to the alternative space of a traditional hypothesis test.")
VSRs have treatments with a variety of treatment effects, usually with
treatment arms simulated to be better than control.

If an external file is used to specify the subject responses to be simulated,
it replaces the dose response, longitudinal, and baseline profiles specified
in an explicitly defined VSR tab. An entire sequence of visit responses for a
subjects is drawn from the uploaded patient responses file. This is elaborated
on more in each endpoint's VSR description.

Each endpoint type (Continuous, Dichotomous, and Time-to-event) has its own
method for specifying the dose response VSR and the visit to visit correlation.
