
# The summary results columns

## Highlights

These are the columns displayed on the simulations tab after simulations
are completed, the can also be displayed in the separate "Highlights"
results window.

+----------+---------+------------------------------------------------+
| Column   | Number  | Description                                    |
| Title    | of      |                                                |
|          | columns |                                                |
+==========+=========+================================================+
| Select   | 1       | Not an output column, this column contains     |
|          |         | check box to allow the user to select which    |
|          |         | scenario to simulate. The 'Select All' button  |
|          |         | causes them all to be checked.                 |
+----------+---------+------------------------------------------------+
| Status   | 1       | This column reports on the current status of   |
|          |         | simulations: Completed, Running, No Results,   |
|          |         | Out of date, Error. It is updated              |
|          |         | automatically.                                 |
+----------+---------+------------------------------------------------+
| Scenario | 1       | This column gives the name of the scenario,    |
|          |         | concatenating together the profile names from  |
|          |         | the following tabs:                            |
|          |         |                                                |
|          |         | 'Execution \> Accrual',                        |
|          |         |                                                |
|          |         | 'Execution \> Dropout Rate',                   |
|          |         |                                                |
|          |         | 'Virtual Subject Response \> Composite,        |
|          |         |                                                |
|          |         | This is the same name as used for the results  |
|          |         | directory                                      |
+----------+---------+------------------------------------------------+
| Random   | 1       | Base random number seed used to perform the    |
| Number   |         | simulations.                                   |
| Seed     |         |                                                |
+----------+---------+------------------------------------------------+
| Num Sims | 1       | The number of simulations that were run to     |
|          |         | produce the displayed results.                 |
+----------+---------+------------------------------------------------+
| Mean     | 1       | This is the mean (over the simulations) of the |
| Subj.    |         | number of subjects recruited in this scenario. |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | This is the proportion of simulations that     |
| Overall  |         | stopped for success, either early success or   |
| Success  |         | late success (as defined below).               |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | This is the proportion of simulations that     |
| Early    |         | stopped early for success (and did not regress |
| Success  |         | to futility in the final analysis -- though    |
|          |         | they might have regressed to 'inconclusive').  |
+----------+---------+------------------------------------------------+
| Ppn Late | 1       | This is the proportion of simulations that did |
| Success  |         | not stop early but were successful in the      |
|          |         | final analysis.                                |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | This is the proportion of simulations that     |
| Overall  |         | stopped for futility, either early futility or |
| Futility |         | late futility (as defined below).              |
+----------+---------+------------------------------------------------+
| Ppn Late | 1       | This is the proportion of simulations that did |
| Futility |         | not stop early but were futile in the final    |
|          |         | analysis.                                      |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | This is the proportion of simulations that     |
| Early    |         | stopped early for futility (and did not        |
| Futility |         | regress to success in the final analysis --    |
|          |         | though they might have regressed to            |
|          |         | 'inconclusive').                               |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | This is the proportion of simulations that     |
| S        |         | stopped early for success but regressed to     |
| uc-\>Fut |         | futility in the final analysis.                |
| Flipflop |         |                                                |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | This is the proportion of simulations that     |
| F        |         | stopped early for futility but regressed to    |
| ut-\>Suc |         | success in the final analysis.                 |
| Flipflop |         |                                                |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | This is the proportion of simulations that did |
| Inco     |         | not stop early and were neither successful nor |
| nclusive |         | futile in the final analysis.                  |
+----------+---------+------------------------------------------------+
| Early    | 1       | This is the average time to an early decision  |
| Success  |         | to stop for success (i.e. the time excluding   |
| Time     |         | final follow up) over those simulations that   |
|          |         | did decide early to stop for success.          |
+----------+---------+------------------------------------------------+
| Mean     | One per | This is the mean (over the simulations) of the |
| Trt.:    | arm     | estimate of the response on this dose.         |
| \<Dose\> |         |                                                |
+----------+---------+------------------------------------------------+
| Mean     | 1       | This is the mean, in weeks (over the           |
| Duration |         | simulations) of the duration of the trial from |
|          |         | first patient first visit to last patient last |
|          |         | visit                                          |
+----------+---------+------------------------------------------------+
| PPn Arms | One per | This is the number of times (over the          |
| Drop:    | arm     | simulations) that each arm was dropped.        |
| \<       |         |                                                |
| Dose\>\> |         |                                                |
+----------+---------+------------------------------------------------+
| Mean LP  | 1       | This is the mean, in weeks (over the           |
| Enrolled |         | simulations) of the duration of the trial from |
|          |         | first patient first visit to Last Patient      |
|          |         | First Visit (i.e. the duration of accrual).    |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | The proportion of simulations that met the     |
| Correct  |         | success criteria and selected (by the target   |
| Arm      |         | QOI specified on the Study \> Variant tab) one |
|          |         | of the arms marked as "should succeed" on the  |
|          |         | Virtual Subject Response \> Explicitly Defined |
|          |         | \> Dose Response tab                           |
+----------+---------+------------------------------------------------+
| Ppn      | 1       | The proportion of simulations that met the     |
| I        |         | success criteria and selected (by the target   |
| ncorrect |         | QOI specified on the Study \> Variant tab) one |
| Arm      |         | of the arms **not** marked as "should succeed" |
|          |         | on the Virtual Subject Response \> Explicitly  |
|          |         | Defined \> Dose Response tab                   |
+----------+---------+------------------------------------------------+
| Version  | 1       | The FACTS version number at the time the       |
|          |         | simulations were run.                          |
+----------+---------+------------------------------------------------+

: Figure 4‑4 - Example design notes

## Allocation

+----------+---------+------------------------------------------------+
| Column   | Number  | Description                                    |
| Title    | of      |                                                |
|          | columns |                                                |
+==========+=========+================================================+
| Status   | 1       | This column reports on the current status of   |
|          |         | simulations: Completed, Running, No Results,   |
|          |         | Out of date, Error. It is updated              |
|          |         | automatically.                                 |
+----------+---------+------------------------------------------------+
| Scenario | 1       | This column gives the name of the scenario,    |
|          |         | concatenating together the profile names from  |
|          |         | the following tabs:                            |
|          |         |                                                |
|          |         | 'Execution \> Accrual',                        |
|          |         |                                                |
|          |         | 'Execution \> Dropout Rate',                   |
|          |         |                                                |
|          |         | 'Virtual Subject Response \> Composite,        |
|          |         |                                                |
|          |         | This is the same name as used for the results  |
|          |         | directory                                      |
+----------+---------+------------------------------------------------+
| Mean     | 1       | This is the mean (over the simulations) of the |
| Subj.    |         | number of subjects recruited in this scenario. |
+----------+---------+------------------------------------------------+
| SD Mean  | 1       | This is the standard deviation across the      |
| Subj.    |         | simulations of the number of subjects          |
|          |         | recruited.                                     |
+----------+---------+------------------------------------------------+
| Num Subj | 1       | This is the eightieth percentile across the    |
| 80%      |         | simulations of the number of subjects          |
|          |         | recruited into the trial.                      |
+----------+---------+------------------------------------------------+
| Mean     | One per | This is the mean (over the simulations) of the |
| Alloc.:  | arm     | number of subjects recruited into each arm in  |
| \<Dose\> |         | this scenario.                                 |
+----------+---------+------------------------------------------------+
| SD       | One per | This is the SD (over the simulations) of the   |
| Alloc.:  | arm     | number of subjects allocated to each treatment |
| \<Dose\> |         | arm.                                           |
+----------+---------+------------------------------------------------+

: Figure 6‑1: Webservice Configuration

## Response

+----------+---------+------------------------------------------------+
| Column   | Number  | Description                                    |
| Title    | of      |                                                |
|          | columns |                                                |
+==========+=========+================================================+
| Status   | 1       | This column reports on the current status of   |
|          |         | simulations: Completed, Running, No Results,   |
|          |         | Out of date, Error. It is updated              |
|          |         | automatically.                                 |
+----------+---------+------------------------------------------------+
| Scenario | 1       | This column gives the name of the scenario,    |
|          |         | concatenating together the profile names from  |
|          |         | the following tabs:                            |
|          |         |                                                |
|          |         | 'Execution \> Accrual',                        |
|          |         |                                                |
|          |         | 'Execution \> Dropout Rate',                   |
|          |         |                                                |
|          |         | 'Virtual Subject Response \> Composite,        |
|          |         |                                                |
|          |         | This is the same name as used for the results  |
|          |         | directory                                      |
+----------+---------+------------------------------------------------+
| Mean     | One per | This is the mean (over the simulations) of the |
| Trt.:    | arm     | estimate of the response on this dose.         |
| \<Dose\> |         |                                                |
+----------+---------+------------------------------------------------+
| SD Trt.: | One per | This is the standard deviation (over the       |
| \<Dose\> | arm     | simulations) of the estimate of the response   |
|          |         | on this dose.                                  |
+----------+---------+------------------------------------------------+
| True     | One per | This is the true response rate from which the  |
| Mean     | arm     | simulation data was sampled.                   |
| Resp:    |         |                                                |
| \<Dose\> |         |                                                |
+----------+---------+------------------------------------------------+

: Figure 6‑2 The R Configuration Dialog

## Observed

+----------+---------+------------------------------------------------+
| Column   | Number  | Description                                    |
| Title    | of      |                                                |
|          | columns |                                                |
+==========+=========+================================================+
| Status   | 1       | This column reports on the current status of   |
|          |         | simulations: Completed, Running, No Results,   |
|          |         | Out of date, Error. It is updated              |
|          |         | automatically.                                 |
+----------+---------+------------------------------------------------+
| Scenario | 1       | This column gives the name of the scenario,    |
|          |         | concatenating together the profile names from  |
|          |         | the following tabs:                            |
|          |         |                                                |
|          |         | 'Execution \> Accrual',                        |
|          |         |                                                |
|          |         | 'Execution \> Dropout Rate',                   |
|          |         |                                                |
|          |         | 'Virtual Subject Response \> Composite,        |
|          |         |                                                |
|          |         | This is the same name as used for the results  |
|          |         | directory                                      |
+----------+---------+------------------------------------------------+
| Mean     | One per | This is the mean (over the simulations) of the |
| Complete | arm     | number of subjects recruited per arm which     |
| \<Dose\> |         | have had their endpoint observed in this       |
|          |         | scenario.                                      |
+----------+---------+------------------------------------------------+
| Mean     | One per | This is the mean (over the simulations) of     |
| Complete | arm     | information observed per arm as defined on the |
| Info     |         | Interims tab (Subjects enrolled, Complete Data |
| \<Dose\> |         | at Specified Visit, Opportunity to Complete at |
|          |         | Specified Visit) in this scenario.             |
+----------+---------+------------------------------------------------+
| Mean     | One per | This is the mean (over the simulations) of     |
| Dropouts | arm per | dropouts per arm per visit in this scenario.   |
| \<Dose\> | visit   |                                                |
| \        |         |                                                |
| <Visit\> |         |                                                |
+----------+---------+------------------------------------------------+

: Figure 6‑3 Adding a link to R

## Probabilities

+----------+---------+------------------------------------------------+
| Column   | Number  | Description                                    |
| Title    | of      |                                                |
|          | columns |                                                |
+==========+=========+================================================+
| Status   | 1       | This column reports on the current status of   |
|          |         | simulations: Completed, Running, No Results,   |
|          |         | Out of date, Error. It is updated              |
|          |         | automatically.                                 |
+----------+---------+------------------------------------------------+
| Scenario | 1       | This column gives the name of the scenario,    |
|          |         | concatenating together the profile names from  |
|          |         | the following tabs:                            |
|          |         |                                                |
|          |         | 'Execution \> Accrual',                        |
|          |         |                                                |
|          |         | 'Execution \> Dropout Rate',                   |
|          |         |                                                |
|          |         | 'Virtual Subject Response \> Composite,        |
|          |         |                                                |
|          |         | This is the same name as used for the results  |
|          |         | directory                                      |
+----------+---------+------------------------------------------------+
| \<QOI\>  | One per | For each Posterior Probability and Predictive  |
| \<Dose\> | arm per | Probability QOI defined on this endpoint, this |
|          | QOI     | is the mean over the simulations of the        |
|          |         | estimate of the probability of the QOI for     |
|          |         | each dose. (P-value QOIs are reported in the   |
|          |         | frequentist results table).                    |
|          |         |                                                |
|          |         | For each Target QOI this is the proportion of  |
|          |         | simulations where this dose was selected at    |
|          |         | the end of the trial as the dose with the      |
|          |         | greatest probability of meeting the target     |
|          |         | condition.                                     |
|          |         |                                                |
|          |         | The probability that each dose is the target   |
|          |         | at the end of a simulated trial is its         |
|          |         | marginal probability (the number of times it   |
|          |         | was the dose closest to the target in the MCMC |
|          |         | sampling of the analysis at the end of the     |
|          |         | trial). The target of having the Max response  |
|          |         | on this endpoint, or some fraction of it (EDq) |
|          |         | is always identifiable, so the Ppn(target) for |
|          |         | these QOIs will sum to 1 across the doses.     |
|          |         |                                                |
|          |         | An MED target is not guaranteed to be          |
|          |         | identifiable, if no dose meets the CSD         |
|          |         | criteria in any MCMC sample so all doses have  |
|          |         | a 0 probability of having a response greater   |
|          |         | than Control (or AC) by the CSD then no dose   |
|          |         | is the MED. So the sum of each Ppn(target) QOI |
|          |         | across the doses should sum to between 0 and 1 |
|          |         | inclusive.                                     |
|          |         |                                                |
|          |         | Decision QOI's are not reported here           |
|          |         | separately, but their component QOIs -- the    |
|          |         | vector of values and target QOI used to select |
|          |         | from them are.                                 |
+----------+---------+------------------------------------------------+

: Figure 6‑4 Enabling analytics

## Model Parameters

+----------+---------+------------------------------------------------+
| Column   | Number  | Description                                    |
| Title    | of      |                                                |
|          | columns |                                                |
+==========+=========+================================================+
| Scenario | 1       | This column gives the name of the scenario,    |
|          |         | concatenating together the profile names from  |
|          |         | the following tabs:                            |
|          |         |                                                |
|          |         | 'Execution \> Accrual',                        |
|          |         |                                                |
|          |         | 'Execution \> Dropout Rate',                   |
|          |         |                                                |
|          |         | 'Virtual Subject Response \> Composite,        |
|          |         |                                                |
|          |         | This is the same name as used for the results  |
|          |         | directory                                      |
+----------+---------+------------------------------------------------+
| Mean     | D\*V    | These are only calculated and written out if   |
| Longmod  |         | the ITP longitudinal model is being used.      |
| Resp:    |         |                                                |
| \<Dose\> |         | This is the mean (over the simulations) of the |
| \        |         | estimate of the mean response for a particular |
| <Visit\> |         | dose at a particular visit.                    |
+----------+---------+------------------------------------------------+
| SE Mean  | D\*V    | This is the standard error (over the           |
| Longmod  |         | simulations) of the longitudinal model         |
| Resp:    |         | estimate of the response at intermediate       |
| \<Dose\> |         | visits (see above)                             |
| \        |         |                                                |
| <Visit\> |         |                                                |
+----------+---------+------------------------------------------------+
| BAC Mean | 1       | This is the mean (over the simulations) of the |
|          |         | posterior estimate of the mean of the Bayesian |
|          |         | Augmented Control (Hierarchical Prior)         |
|          |         | distribution of mean control responses.        |
+----------+---------+------------------------------------------------+
| SD BAC   | 1       | This is the SD (over the simulations) of the   |
| Mean     |         | posterior estimate of the mean of the Bayesian |
|          |         | Augmented Control (Hierarchical Prior)         |
|          |         | distribution of mean control responses.        |
+----------+---------+------------------------------------------------+
| BAC Tau  | 1       | This is the mean (over the simulations) of the |
|          |         | posterior estimate of the SD of the Bayesian   |
|          |         | Augmented Control (Hierarchical Prior)         |
|          |         | distribution of mean control responses.        |
+----------+---------+------------------------------------------------+
| SD BAC   | 1       | This is the SD (over the simulations) of the   |
| tau      |         | posterior estimate of the SD of the Bayesian   |
|          |         | Augmented Control (Hierarchical Prior)         |
|          |         | distribution of mean control responses.        |
+----------+---------+------------------------------------------------+
| BAAC     | 1       | This is the mean (over the simulations) of the |
| Mean     |         | posterior estimate of the mean of the Bayesian |
|          |         | Augmented Active Comparator (Hierarchical      |
|          |         | Prior) distribution of mean active comparator  |
|          |         | responses.                                     |
+----------+---------+------------------------------------------------+
| SD BAAC  | 1       | This is the SD (over the simulations) of the   |
| Mean     |         | posterior estimate of the mean of the Bayesian |
|          |         | Augmented Active Comparator (Hierarchical      |
|          |         | Prior) distribution of mean control responses. |
+----------+---------+------------------------------------------------+
| BAAC Tau | 1       | This is the mean (over the simulations) of the |
|          |         | posterior estimate of the SD of the Bayesian   |
|          |         | Augmented Active Comparator (Hierarchical      |
|          |         | Prior) distribution of mean active comparator  |
|          |         | responses.                                     |
+----------+---------+------------------------------------------------+
| SD BAAC  | 1       | This is the SD (over the simulations) of the   |
| tau      |         | posterior estimate of the SD of the Bayesian   |
|          |         | Augmented Active Comparator (Hierarchical      |
|          |         | Prior) distribution of mean active comparator  |
|          |         | responses.                                     |
+----------+---------+------------------------------------------------+




### QOI Columns

The QOI columns depend on the QOIs that have been defined for this
design. The columns are grouped in the following order:

Posterior Probabilities The posterior probability for each QOI for each
dose.

Predictive Probabilities The predictive probability for each QOI for
each dose.

P-Values The p-value for each QOI for each dose.

Target Probabilities The probability of being the target for each QOI
for each dose.

Decision QOIs The value of the decision QOI at the target.

Success

Futile A flag for each QOI decision criteria indicating if the decision
QOI was evaluated and compared to a threshold at the interim (weeks
file) or final analysis (simulation file). The flag value is -1 if the
decision QOI was not evaluated, 0 if it did not meet the threshold and 1
if it did.

Success / Futile Combined A flag indicating if the interim or final
analysis determined success or futility taking all the factors defined
for Success/Futility into account: 0 if the conditions were not met, 1
it the conditions were met. If success and futility conditions have been
defined that are not mutually exclusive and both sets of combined
conditions are met, FACTS will pick one of the outcomes as met but not
the other. In order to discourage defining Success and Futility rules
that can both be true FACTS does not guarantee which outcome will be
selected.

## Contents of Simulations_freq\_\<missing\>.csv, Weeks_freq\_\<missing\>.csv

These file contain the frequentist results after an interim analysis
(weeks file) or final analysis (simulations file), apart for the first
column, the columns are the same in the two types of file, and the same
across the different methods for treating missing data.

  -----------------------------------------------------------------------
  Column      Number of Description
  Title       columns
  ----------- --------- -------------------------------------------------
  \# Trial    1         The number of the simulation.
                        (simulations_freq\_\...csv only)

  #Weeks      1         The week of the interim (weeks_freq\_\...csv
                        only)

  Theta       D         Unadjusted estimate of response per treatment arm
  \<dose\>

  Theta SD    D         The SD of the estimate of response per treatment
  \<dose\>              arm

  Trt Effect  D         The relative size of the treatment effect
  \<dose\>              compared to control per arm (treatment effect for
                        control is always 0). The direction of the
                        comparison takes into account whether a response
                        represents a subject's condition improving or
                        worsening, so that a positive treatment effect
                        shows the response on the dose is better than on
                        control.

  t-Stat      D         The test statistic per treatment arm (for control
  \<dose\>              this is always 0)

  p-Value     D         The unadjusted test statistic p-value per arm
  \<dose\>              (for control this is always 0)

  lower CI    D         The unadjusted lower bound of the alpha
  \<dose\>              confidence interval of the estimated treatment
                        effect per treatment arm (for control this is
                        always 0).

  upper CI    D         The unadjusted upper bound of the alpha
  \<dose\>              confidence interval of the estimated treatment
                        effect per treatment arm (for control this is
                        always 0).

  Min p-Value 1         The smallest of the test statistic p-values

  p-Value     D         The Dunnett adjusted test statistic p-value per
  Dunnett               arm (for control this is always 0).
  \<dose\>

  lower CI    D         The Dunnett adjusted lower bound of the alpha
  Dunnett               confidence interval of the estimated treatment
  \<dose\>              effect (for control this is always 0).

  upper CI    D         The Dunnett adjusted upper bound of the alpha
  Dunnett               confidence interval of the estimated treatment
  \<dose\>              effect (for control this is always 0).

  Min p-Value 1         The smallest of the Dunnett adjusted p-values.
  Dunnett

  p-Value     D         The Bonferroni adjusted test statistic p-value
  Bonf                  per arm.
  \<dose\>

  lower-CI    D         The Bonferroni adjusted lower bound of the alpha
  Bonf                  confidence interval of the estimated treatment
  \<dose\>              effect (for control this is always 0).

  upper-CI    D         The Bonferroni adjusted upper bound of the alpha
  Bonf                  confidence interval of the estimated treatment
  \<dose\>              effect (for control this is always 0).

  Min p-Value 1         The smallest of the Bonferroni adjusted test
  Bonf                  statistic value per arm.

  t-Stat      1         The t statistic from the trend test.
  trend

  p-Value     1         The p-value from the trend test.
  trend
  -----------------------------------------------------------------------

  : Figure 7‑3: Virtual Subject Dichotomous Longitudinal Response

## Contents of PatientsNNNNN.csv

  -------------------------------------------------------------------------
  Column Title Number of  Description
               columns
  ------------ ---------- -------------------------------------------------
  #Subject     1          The subject id number, starting at 1.

  Region       1          Which region the subject was recruited in

  Date         1          The date, in weeks from the start of the trial,
                          of the subject's baseline visit and
                          randomization.

  Dose         1          The index number (1, ...) of the treatment arm
                          the subject belongs to.

  LastVisit#              The index of the last visit for which the
                          subjects data was collected, if the subject did
                          not complete this could be because the subject
                          dropped-out, the subject's treatment arm was
                          dropped (and there was no follow-up) or the study
                          stopped early (and there was no follow-up).

  Baseline     1          -9999 there is no baseline for subjects in a
                          dichotomous response trial.

  Visit        V          Subjects response at each visit
  \<visit\>
  -------------------------------------------------------------------------

  : Figure 7‑4: Restricted Markov Dose Response

## Contents of MCMCNNNNN.csv

The MCMC file if requested for output by the user, contains all the MCMC
samples for the fitted parameters in the design. There is one row per
sample (including the burnin) and the samples from all the analyses in
the simulation are included. The first two columns are the analysis
index and the sample (within analysis) index. The remaining columns are
the parameters whose sample values are being reported, the number and
constituents of these columns are highly variable depending on design of
the statistical analysis.

### Content if using a conventional Dichotomous endpoint

  ------------------------------------------------------------------------
  Column      Number of  Description
  Title       columns
  ----------- ---------- -------------------------------------------------
  Analysis    1          The index of the analysis (interim) in the
                         simulation

  Sample      1          The index of the sample within the analysis

  Pi \<dose\> D          The estimate of the response rate for each dose,
                         based on the dose response model fitted

  A \<1-8\> / P          If the dose response model estimates parameters
  Tau                    then the samples of these are listed next. The
                         number and name of the parameters will vary
                         depending on the model being fitted. Check the
                         Design \> Dose Response tab for a listing of the
                         parameters.

  Longmod     L \* P \*  If the analysis includes longitudinal modelling
  \<model\>   V          then the samples of the parameters of the
  \<param\>              longitudinal models are output. The number of
  \<visit\>              models depends on the number of different
                         longitudinal fits the user has specified (one
                         over all arms, one for control and one for all
                         treatment arms, model all arms separately, etc.),
                         the number of parameters the model has, and if
                         these are fitted per visit (which depends on the
                         model being fitted), then the number of visits.
  ------------------------------------------------------------------------

  : Figure 7‑9: External Data

### Contents if using a Restricted Markov endpoint

  ------------------------------------------------------------------------
  Column      Number of  Description
  Title       columns
  ----------- ---------- -------------------------------------------------
  Analysis    1          The index of the analysis (interim) in the
                         simulation

  Sample      1          The index of the sample within the analysis

  Pi \<Dose\> D          The estimate of the response rate for each dose,
                         based on the dose response model fitted

  A \<1-8\> / P          If the dose response model estimates parameters
  Tau                    then the samples of these are listed next. The
                         number and name of the parameters will vary
                         depending on the model being fitted. Check the
                         Design \> Dose Response tab for a listing of the
                         parameters.

  Longmod     L \* P \*  Currently the values of Alpha0, Alpha1, AlphaS
  \<model\>   V          (the parameters to the Dirichlet distribution)
  \<param\>              are (unnecessarily -- these values are not
  \<visit\>              sampled) output, along with the values for P0, P1
                         and PS the transition probabilities of each model
                         at each visit.
  ------------------------------------------------------------------------

  : Figure 7‑10 External Data directory

### Contents if using a Dichotomized Continuous variable

These are the same as for the Dichotomous endpoint, but the LM
parameters are for the LM of the continuous response value.

[^1]: Screenshots from earlier versions of FACTS 6 are retained only
    where they are unchanged in FACTS 7.1

[^2]: The doses in the design become linked to many other parameters, if
    dose levels could be edited this could change the effective order of
    doses and keeping the other parameters settings associated with the
    right doses becomes problematic -- in different circumstances the
    user might want values to stay with the particular treatment arm or
    stay with the particular slot in the treatment arm ranking. Forcing
    doses to be deleted and re-entered if their dose level changes

[^3]: Elsewhere in FACTS Core however we still use the overly specific
    term "dose" when the user might be simulating any manner of
    different treatments. Unfortunately the term "dose" became so
    ubiquitous in the user interface, documentation and outputs that it
    will be a lot of work to remove it.

[^4]: This value is in weeks from FACTS 7.0 onwards, previously it was
    in days.

[^5]: This value is in weeks from FACTS 7.0 onwards, previous to that it
    was in days.
