---
title: "Enrichment Designs"
subtitle: "Overview of the capabilities of the FACTS Enrichment Design Engine."
title-block-banner: '#125740'
title-block-banner-color: white
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: false
    number-depth: 4
---

# Scope of this User Guide

This document covers the design options that are common across the three FACTS Enrichment Design Engines: Continuous, Dichotomous and Time-to-Event. Some design elements are shared across design engines, in which case there is only a single description of them. Others differ based on the endpoint used, in which case separate pages have been created to describe each.

The screenshots provided are specific to a particular installation and <span class="custom-tooltip"> may not reflect the exact layout <span class="tooltip-text">Screenshots from earlier versions of FACTS 6 are still used only when the tabs they show are unchanged in FACTS 7.1.</span> </span> of the information seen by any particular user. They were taken from FACTS V7 & V6 installed on Windows 10 or 11. If FACTS is installed on different versions of Windows, or with different Windows ‘themes’ there will be some differences in appearance introduced by Windows. The contents of each tab, however, will generally be consistent with the screenshots in this document.

## FACTS Version

This is the version of the user guide for inclusion with the FACTS 7.1 release.

## Citing FACTS

Please cite FACTS wherever applicable using [this citation](../../../../introduction/citation.qmd).

# FACTS Core Overview

FACTS Enrichment Designs (ED) is for simulating trials where there are a number of related treatments being tested in parallel. This is anticipated to be the same drug but tested in different ways – for instance in different (sub) populations or different indications. Thus this can be used for trials in personalised medicine where there might be a biomarker positive and biomarker negative populations, or trials of a drug where different populations (such as old and young, or mild and severe disease) might have a different response to the treatment or on control, or the same compound is being tested in different but related indications, for instance different types of pain or inflammation.

These trials are essentially composed of parallel trials that in FACTS ED we generically refer to as ‘groups’ – so a group is a different sub-population or indication. The study drug is tested in each group either compared to a historical control response or against a control tested in that group. 

FACTS provides numerous options for the statistical analysis, some of them straight forward, some of them quite novel, though all have been used in actual trials:
-	The endpoint can be continuous, dichotomous or time to event.
-	Interims can be specified at fixed intervals by time, the number of
  subjects recruited, or the amount of information observed.
-	At interims individual groups or the whole study can be stopped for success or futility.
-	With either a dichotomous or continuous endpoint, early interim measures can be used to impute the patient’s likely final outcome. This can be used when final endpoint data is missing due to subject dropout or at interims for subjects who’ve not reached their final endpoint yet.
-	Estimation of the response on the control arm can be augmented using a hierarchical model to borrow from data from previous studies.
-	There is an across group analysis that analyzes the relative difference between treatment and control in each group.
-	Estimation of the response on the control or the treatment can be augmented by using a hierarchical borrowing across the groups.


The main tabs in FACTS ED:

The Study Tab
: The Study Tab is used for entering the main characteristics of the
study and specifying the treatment arms to be tested in the study.
This is where the user specifies the 'given' requirements, or
constraints, of the trial to be designed.

Virtual Subject Response
: The VSR tabs are for specifying the simulation
of subject responses. This is either by specifying assumed efficacy scenarios
for each treatment arm, or by supplying external data files
of simulated subject responses.

Execution
: The Execution tab is for specifying operational properties of the trial's
execution to simulate. Specifically, the rate of subject accrual and
the probability of subjects dropping out.

Design
: The Design tabs are for specifying the statistical analysis and adaptive
design rules. These are the design choices available to the trial
biostatistician and include how to model the final responses, allocation rules,
missing or unobserved data handling, what decisions to
make at interims, and how to determine if the overall trial has been
successful.

Simulation
: The simulation tab is for the user to set up and run simulations. It also
allows for viewing of the simulation results either as output simulation files
or pre-made graphics that provide many summaries of the simulation outcomes.

Analysis
: On the Analysis tab, the user can load an example data set and view
the results of the FACTS analysis of that data using the current
specified design. This tab is useful for implementation of a design that was
simulated in FACTS.

Many of the above tabs also has sub-tabs that help with configuring the specifics
of the design simulations. These sub-tabs are described in detail in the tab-
specific portions of the user guide.
