---
title: "Dirichlet Prior(s) and Dose Response for Ordinal Trials"
subtitle: "A description of the ordinal specific design tabs, Dirichlet Prior and OTHERS IF NECESSARY."
title-block-banner: '#125740'
title-block-banner-color: white
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: false
    number-depth: 4
---

The ordinal engine's first design tab allows the user to define prior exponents 
for Dirichlet distributions.  If the user has selected independent Dirichlets on
the Study Info tab for ordinal outcome modeling, each experimental arm gets its 
own set of exponents.  If the user has selected cumulative logistic modeling, 
only the control arm gets a set of exponents, and the prior distributions for 
other experimental arms are derived from this one set of exponents and the prior 
distributions for the dose-response model parameters.  

Prior exponents for Dirichlet distributions are often interpreted as counts of 
subjects observed in an earlier experiment, but positive non-integer values are 
allowed. 

The prior mean for the probability of a given ordinal outcome under the Dirichlet 
distribution is the exponent corresponding to that outcome, divided by the sum 
of the exponents.  For example, if there are four ordinal outcomes and the prior 
exponents are 10, 20, 30, and 40, the prior probabilities of the four outcomes 
are 0.1, 0.2, 0.3, and 0.4.  

If a relatively non-informative prior distribution is desired, one suggestion 
is to use equal exponents that add up to approximately 0.8, i.e. $0.8/K$ where $K$
is the number of ordinal outcomes (Berger, Bernardo, and Sun, Bayesian Analysis 2015).  