---
title: "FACTS 8.1.0 Release Notes"
subtitle: "March 17, 2026"
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
---

# Introduction

FACTS 8.1.0 is now available for download via [FACTS Cloud](https://factscloud-live.azurewebsites.net/). Its main new features are:

- Two new Quick Starts to facilitate the creation of Promising Zone and Goldilocks designs.
- Seamless Phase 2/3 designs using ordinal endpoints.
- In Group Sequential Quick Starts, the ability to specify binding/non-binding futility rules.
- New operational QOIs tracking the trial status and additional comparison operators to facilitate their usage.

# Phase 2 and Phase 3 Quick Start Improvements

- Two new Quick Starts have been created to speed up and simplify the process of creating common trial design types, available for continuous, dichotomous or time-to-event endpoints. The "Promising Zone" Quick Start generates a FACTS design with a two-stage sample size re-estimation based on interim conditional power results. The "Goldilocks" Quick Start generates a FACTS design using Bayesian predictive probabilities to assess the likelihood of success or futility at interim stages, particularly suited for trials with delayed endpoint observation.
- In Group Sequential Quick Starts, users can now specify whether futility rules are binding or non-binding. By default, the rules are non-binding.
- For all Quick Starts, the virtual subject response profiles have been standardised to ease comparison of the different designs.

# Phase 2 and Phase 3 Trial Type Improvements

- In Phase 2 and Phase 3 designs, users can now create operational QOIs tracking the trial status, and use these as part of decision rules. The trial status operational QOIs include: whether the trial is still accruing participants, whether the trial has reached the max sample size, whether the trial has stopped early for success/futility/graduation, and the interim number of early stopping.
- In Phase 2 and Phase 3 designs, additional comparison operators when comparing QOIs against threshold values have been added. Users can now use the following comparison operators: '<', '<=', '=', '>=', '>'.    
- In Phase 2 and Phase 3 designs, the creation of a new Posterior Probability QOI, Predictive Probability QOI, p-value QOI and Operational QOI will now automatically create a corresponding Decision QOI evaluated at a sensible default target.    
- In Phase 2 and Phase 3 designs, the "QOIs per Interim" scenario results graph will now display the number of outcome types at each interim (success, futility, inconclusice, etc.) as well as the number of simulations that have reached the given interim. 
- In Phase 2 and Phase 3 designs, the "QOIs per Interim" scenario results graph will now handle the display of simulations with flip-flop outcomes (Success->Futility, Futility->Success) correctly.
- In Phase 2 and Phase 3 designs, the "Per Sim: Interim Info" scenario results graph will correctly extend the subject information plots (enrolled, completers, dropouts, etc.) to the final analysis when the trial has stopped early but has follow-up.
- In Phase 2 and Phase 3 designs, existing design loaded into FACTS with an invalid setting for the dose response model 'Model Control Separately' parameter will be rectified upon load.
- In Phase 2 and Phase 3 designs, the "Dose Response" tab sampled graphs of the prior will be displayed correctly for the "Simple Hierarchical" and "Hierarchical Three-Parameter Logistic" models.
- In Phase 2 and Phase 3 designs, the "Dose Response" tab graphs will always display the Control and Active Comparator (AC) arms.
- In Phase 2 and Phase 3 designs, the "Hierarchical Priors" tab for the active comparator arm will now correctly add entries to the prior study sufficient statistics.
- In Phase 2 and Phase 3 designs, designs using the 2D NDLM Dose Response model (available when enabling 2D factorial dose combinations) will now output simulation results which are consistent between running on Windows and Linux systems.
- In Phase 2 and Phase Multiple Endpoint designs, loading an existing design and adding default QOIs to it will no longer result in FACTS erroring upon simulation.
- In Seamless Phase 2/3 designs, the "QOIs per Interim" scenario results graph will correctly handle the display of early/late graduation from Stage 1 to Stage 2 outcomes.
- In Seamless Phase 2/3 designs, the "Per Sim: Interim Info" scenario results graph will correctly handle the display of simulations which have stopped in Stage 1.
- In Seamless Phase 2/3 designs, the complete data analysis (CDA) Stage 1 summary file will now correctly match header columns with the underlying data.
- In Seamless Phase 2/3 designs, a new "Outcome" results summary graph is available across all scenarios and within the "Overall" graphing section of a given scenario. This graphs displays the proportion of all outcomes that have occurred across the entire trial, broken down by stage.
- In Seamless Phase 2/3 designs, timed interims in the second stage will now be handled more robustly, ensuring that stage 2 interims will not “back up” to a stage 1 time for initial analysis. [IMPACTS OLDER DESIGNS]
- In Seamless Phase 2/3 designs, designs older than FACTS 7.1.1 which have not correctly applied the "Mirror Stage 1 in Stage 2" functionality for Dose Response models will now have this setting applied correctly. [IMPACTS OLDER DESIGNS]
- In Seamless Phase 2/3 Multiple Endpoint designs, older designs using the global frequentist tab option 'Missing data will be imputed as failure' erroenously for continuous endpoints will now simulate correctly.

# Enrichment and Basket Trial Type Improvements

# Platform Trial Improvements

- In Platform Trial designs, the "QOIs per Update" scenario results graph will now display the number of outcome types at each interim (success, futility, inconclusice, etc.) as well as the number of simulations that have reached the given update.
- In Platform Trial designs, the "QOIs per Update" and "Per Sim: Interim Info" scenario results graph will now handle the display of simulations with flip-flop outcomes (Success->Futility, Futility->Success, Success->Inconclusive, Futility->Inconclusive) and "late" outcomes (Late Success, Late Futility, Inconclusive) correctly.
- In Platform Trial designs, changing a non-default QOI to a default QOI (when the referenced QOI is used in stopping criteria) will no longer result in simulation errors.
- In Platform Trial designs, additional comparison operators when comparing QOIs against threshold values have been added. Users can now use the following comparison operators: '<', '<=', '=', '>=', '>'. 

# Phase 1 Dose Escalation Trial Type Improvements

- In CRM designs, when both the MED and MTD are estimated to be above the investigated dose range, the selected OSD is now -1, i.e. none of the investigated doses is selected as OSD. [IMPACTS OLDER DESIGNS]
- In 2D-CRM designs, running an analysis via the Analysis tab for a design using a custom run-in will now output the correct dose recommendations.

# General Improvements

- The runtime memory usage of FACTS has been improved significantly. In particular, the number of Graphic Device Interface (GDI) objects used by FACTS has been reduced significantly when opening multiple designs with the same instance of FACTS.
- Cancelling simulations when there are existing scenarios that have been successfully simulated will no longer result in the "Across Scenario" graph popping up erroneously multiple times.
- The time taken to generate simulation scenarios when creating new simulation profiles has been improved. This becomes particularly noticeable when the design contains a large number of simulations scenarios, some of which have been already simulated. 
- If crash/analytics data sharing is enabled (Settings > Options > Analytics), the shared data will contain the user's organization name in order to improve user experience.

Please [contact us](../../../contact/index.qmd) regarding any questions.