---
title: "FACTS 8.0.0 Release Notes"
subtitle: "September 30, 2025"
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
---

# Introduction

FACTS 8.0.0 is now available for download via [FACTS Cloud](https://factscloud-live.azurewebsites.net/). Its main new features are:

- Ordinal endpoint support for phase 2 and phase 3 Trial Types. 
- "Fixed Trial" and Group Sequential "Quick Starts" for continuous, dichotomous and time-to-event endpoints to speed up and simplify the process of creating common trial design types.
- Flexible AND/OR Decision Rules for Core, Staged and Platform Trial designs.
- New Operational QOIs.

# FACTS Core and Staged Improvements

- In Core designs, users can now design and simulate trials whose endpoint is on an ordinal scale. In particular, FACTS makes it particularly easy to compare a design using an ordinal endpoint with one which dichotomizes the endpoint. FACTS provides both a cumulative logistic model for ordinal outcome modelling as well as a Dirichlet model.
- Two new "Quick Starts" have been created to speed up and simplify the process of creating common trial design types, available for continuous, dichotomous or time-to-event endpoints. The "Fixed Trial" Quick Start generates a FACTS design with the appropriate maximum sample size given the user specified treatment effect and power for the trial. The "Group Sequential" Quick Start generates a FACTS design with the appropriate group sequential success and futility boundaries derived from the relevant alpha and beta spending functions (Hwang-Shih-DeCani, O'Brian-Fleming, Pocock).
- In Core and Staged designs, users can now specify complex decision rules for early success, early futility, early graduation to Stage 2 and the final analysis; where a subset of criteria can be combined by AND-ing them together whilst others can by OR-ed together. One major use case of this feature is that, in combination with the addition of Operational QOIs, users can now easily design and simulate Bayesian Goldilocks designs.
- In Core and Staged designs, users can now create "Dropout rate" Operational Quantities of Interest (QOIs) and use these in decision rules.
- In Core and Staged designs, the minimum information required to evaluate the decision rules at an interim has been removed. Instead, Operational QOIs can be used in decision rules to ensure that we only make decisions if there is enough information. [BREAKING CHANGE]
- In Core and Staged designs, decision rules will now display the correct comparison against its threshold for upper bounds by displaying "<=" instead of "<". This is of particular importance for decision rules making use of non-probabilistic QOIs (e.g. Subjects Enrolled).
- In Time-to-Event Core and Staged designs, users can now create a number of Operational QOIs based of the design's predictor. For Continuous/Dichotomous predictors, users can now create "Predictor Completer" and "Predictor Opportunity to Complete" Operational QOIs; for time-to-event predictors, user can now create "Predictor Exposure" and "Predictor Event" Operational QOIs.
- In Time-to-Event Staged designs, the max event cap in stage 2 will be respected when the Study Info tab option: "Subjects included in Stage 2 followed-up using Stage 2 rules" is set. 

# FACTS Enrichment Design Improvements


# FACTS Platform Trial Improvements

- In Platform Trial designs, users can now specify complex decision rules for defining a treatment's early success, early futility and its final analysis; where a subset of criteria can be combined by AND-ing them together whilst others can by OR-ed together.
- In Platform Trial designs, opening existing designs will now handle the adding of the Pr(Max) Target Dose QOI correctly.
- In Platform Trial designs, decision rules will now display the correct comparison against its threshold for upper bounds by displaying "<=" instead of "<".

# FACTS Dose Escalation Improvements

- In Rule-based DE designs using BOIN, the escalation and de-escalation bounds will now be displayed on the Design tab.
- In Rule-based DE designs using BOIN, the overdose control rules eliminating a dose from further allocation is now correctly applied when at least three subjects have been assigned to this dose.
- In Rule-based DE designs using 3+3, the reported simulation and cohort results in the GUI will be displayed correctly.
- In Rule-based DE designs using 3+3, the selected MTD will now be displayed in the Allocation History plot.
- In Rule-based DE designs, the Across Scenario "Selected MTD" graph will now colour each dose's selected MTD proportion correctly.
- In CRM DE designs, the Across Scenario "Selected MTD" graph will now colour each dose's selected MTD proportion correctly when the dose's true toxicity falls on the boundary of a toxicity band.

# General Improvements

- The runtime memory usage of FACTS has been reduced significantly, with the initial loading of FACTS requiring 75% less memory.


Please [contact us](../../../contact/index.qmd) regarding any questions.