---
title: "Design Overview"
subtitle: "Description of what is generally specified in the design tab."
title-block-banner: '#125740'
title-block-banner-color: white
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Table of Contents"
    number-sections: false
    number-depth: 4
---

The FACTS core engine allows for the design and simulation of fixed and
adaptive clinical trials, especially focused on, but not limited to,
Bayesian designs with multiple active arms.

# Sub-tabs of the Design Tab

Trials designed in the core
engines are comprised of a number of elements:

1.  [The dose response model](doseresponse.qmd): the user must specify how the doses are related to each other in the primary analysis, though there is a simple ‘no model’ option that estimates
    the mean treatment effect of each arm independently. A fixed trial
    uses the dose response model for the final Bayesian analysis of the
    data; an adaptive trial uses the same model both for the final
    analysis and at the interim updates. For time-to-event endpoints, there is
    an additional tab for estimating the control arm hazard rate called [hazard model](hazardmodel.qmd).
    For ordinal endpoints, there is an additional tab for specifying the 
    [Dirichlet prior](dirichletprior.qmd) parameters.   

2.  [Frequentist analysis](frequentistanalysis.qmd): frequentist p-values can be calculated
    comparing each dose to the control arm (or a fixed value if there is no control). P-values can be used as decision making quantities at interim updates or final analyses. p-value cannot benefit from the dose reponse models or longitudinal models, which are specific to the Bayesian model in FACTS.

3.  The [longitudinal model](../longitudinalmodels/index.qmd) or [predictor model](../longitudinalmodels/tte.qmd): whether the trial is adaptive or
    fixed, the user may select whether to use a longitudinal model for continuous or dichotomous primary endpoints
    or a predictor model when using a time-to-event primary endpoint. In a fixed trial
    the longitudinal model can be used to multiply impute final values for subjects that have dropped out. 
    In an adaptive trial it is also used at the
    interim updates to multiply impute final values for subjects who have been
    recruited but do not yet have final values. In a fixed trial with no
    subject dropouts using a longitudinal model would have no effect on
    the outcome, analysis, or conduct of the trial.

4.  [Allocation rules](allocation.qmd): in a fixed trial the user just specifies the
    proportion of subjects to be recruited to each arm, and the same can
    be done in an adaptive trial (i.e. an adaptive trial does not have
    to adapt the allocation), but an adaptive trial has a range of
    options that the user can use to adapt how subjects are allocated to
    the different treatment arms as the trial progresses.

5.  [Interims](interims.qmd): in an adaptive trial the user specifies how interim 
    analyses are triggered, either by time or by accumulating numbers of subjects 
    enrolled, with complete data, or with opportunity to complete.  The user also 
    specifies whether subjects continue to be followed up after the trial stops at 
    an interim analysis.  In a fixed trial there are no interim analyses and 
    this tab does not apply.  

6.  [Success/Futility Criteria](successfutility.qmd): in an adaptive trial the user can select the
    criteria and specify the thresholds at which the trial should be stopped
    at any interim where the conditions are satisfied. Early stopping is
    optional, and even in an adaptive design the user can opt to always
    recruit the maximum permitted number of subjects. In a fixed trial
    there are no interim analyses and hence no opportunity to stop early. 
    The same Bayesian evaluation criteria are
    available whether the trial is fixed or adaptive. The user selects
    which criteria to use and what thresholds will constitute success or
    failure. The success and failure criteria do not have to be complements of 
    each other, and any analysis that doesn't completely satisfy either the 
    success or futility criteria is labeled "inconclusive."



:::{.callout-tip}

### Design tabs for multiple endpoint designs

The tab layout for multiple endpoint designs is slightly different when compared
to the single endpoint engines. The multiple endpoint engine must allow for
separate Dose Response, Frequentist Analysis, and Longitudinal specifications
for each endpoint.

To allow for this, there is a "Response Models" tab as a first level sub-tab of
the Design tab. There is 1 sub-tab below Response Models for each endpoint. Within
the endpoint tab there will be a Dose Response, Frequentist Analysis, and Longitudinal
tab (if applicable).

:::

# Evaluation of Bayesian Posterior Estimates

At every interim and final analysis there is a Bayesian model fit to the data observed up to that point in the trial. The Bayesian model contains a dose
response model and, often, a longitudinal model. In the absence of a
longitudinal model, the posterior is calculated as:

$$p(\omega|Y) \propto \prod_{i = 1}^{n}{p(y_{i}|\phi)p(\phi)}$$

where $\phi$ is the set of parameters of the selected response model,
$p(\phi)$ is the prior for those parameters, $y_i$ is the
final response for each subject and $n$ is the number of subjects with complete data.

With a longitudinal model, this becomes:

$$p(\omega|Y) \propto \prod_{i = 1}^{n}{p(y_{i}|\phi)p(\phi)\prod_{i = 1}^{n}{\prod_{j = 1}^{L}{p(y_{ij}|\psi)p(\psi)}}}$$

where $\psi$ is the set of parameters of the selected longitudinal model,
$p(\psi)$ is the prior for those parameters, $y_{ij}$ is the
response for each subject $i$ at each visit $j$ and $L$ is the number of visits.

The posterior is evaluated using <span class="custom-tooltip"> MCMC <span class="tooltip-text">Markov Chain Monte Carlo</span> </span> with individual parameters updated
by Metropolis Hastings (or Gibbs sampling where possible), using only
the $y_i$ and $y_{ij}$ data available at the
time of the update.

The likelihood and priors for each of the dose response models are provided
in the description of the [Dose Response tab](doseresponse.qmd), and the
likelihood and priors for the multiple imputation models are provided in
the description of the [Longitudinal Models tab](../longitudinalmodels/index.qmd).
